import { Router, type IRouter } from "express";

const router: IRouter = Router();

const chemicalProcesses = [
  {
    id: "aqua_regia",
    name: "Woda Królewska (HCl + HNO3)",
    nameEn: "Aqua Regia",
    description:
      "Klasyczna metoda odzysku złota i platynowców. WAŻNE: Przed wodą królewską wsad należy najpierw przetrawić w rozcieńczonym HNO3 (25%), aby usunąć miedź, nikiel i inne metale nieszlachetne — dopiero oczyszczony osad poddaje się wodzie królewskiej. Mieszanina HCl:HNO3 (3:1 obj.) rozpuszcza Au, Pt, Pd. Srebro wytrąca się jako AgCl już w trakcie trawienia.",
    targetMetals: ["Au", "Pt", "Pd"],
    reagents: [
      {
        name: "Kwas azotowy rozcieńczony — pre-trawienie (HNO3 25%)",
        formula: "HNO3",
        concentration: 25,
        amountPerKg: 2.0,
        pricePerLiter: 22.0,
      },
      {
        name: "Kwas solny (HCl)",
        formula: "HCl",
        concentration: 35,
        amountPerKg: 3.0,
        pricePerLiter: 18.0,
      },
      {
        name: "Kwas azotowy stężony (HNO3 65%)",
        formula: "HNO3",
        concentration: 65,
        amountPerKg: 1.0,
        pricePerLiter: 28.0,
      },
      {
        name: "Mocznik (rozkład nadmiaru HNO3)",
        formula: "CO(NH2)2",
        concentration: 99,
        amountPerKg: 0.15,
        pricePerLiter: 4.0,
      },
      {
        name: "Wodorosiarczyn sodu — reduktor SMB (wytrącanie Au)",
        formula: "NaHSO3",
        concentration: 40,
        amountPerKg: 0.3,
        pricePerLiter: 12.0,
      },
      {
        name: "Boraks (topnik do wytopu)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.05,
        pricePerLiter: 10.0,
      },
    ],
    temperatureMin: 50,
    temperatureMax: 90,
    temperatureOptimal: 70,
    timePerKgMin: 6,
    timePerKgMax: 18,
    yieldPercent: { Au: 95, Ag: 20, Pt: 85, Pd: 80 },
    electricityKwhPerKg: 0.6,
    safetyNotes:
      "UWAGA: Wydziela trujące opary NOx i HCl. Praca WYŁĄCZNIE pod sprawnym wyciągiem z aktywnym węglem. Wyposażenie: maska z filtrem ABEK P3, rękawice kwasoodporne (nitril/neopren), fartuch kwasoodporny, gogle ochronne. Nigdy nie wlewaj wody do stężonego kwasu!",
    steps: [
      "KROK 0 — BHP: sprawdź wyciąg, załóż maskę ABEK P3, rękawice i gogle",
      "KROK 1 (pre-trawienie HNO3): wsad rozdrobniony zalej rozcieńczonym HNO3 25% (2 L/kg), podgrzej do 40°C przez 2-3h — usuwa Cu, Ni, Pb, Fe, Sn",
      "KROK 2: Odsącz i przemyj osad (Au, Pt, Pd, AgCl, ceramika) wodą destylowaną — filtrat z HNO3 zachowaj do odzysku Ag i Cu",
      "KROK 3 (woda królewska): przygotuj mieszaninę HCl 35% + HNO3 65% w proporcji 3:1 (obj.) w naczyniu PTFE lub szklano-kwasoodpornym",
      "KROK 4: Powoli wsypuj osad do wody królewskiej, podgrzewaj do 60-70°C mieszając co 30 min — Au, Pt, Pd przechodzą do roztworu",
      "KROK 5: Po rozpuszczeniu (4-8h) odsącz ceramikę i AgCl — AgCl odłóż do dalszego odzysku srebra",
      "KROK 6 (rozkład HNO3): Dodaj mocznik CO(NH2)2 porcjami (ok. 1-2 g na 100 ml) aż ustąpią bąbelki — niszczy nadmiar HNO3, który przeszkadza redukcji",
      "KROK 7 (wytrącanie Au): Powoli dodawaj SMB (NaHSO3) do zimnego roztworu — złoto wytrąca się jako brązowy proszek",
      "KROK 8: Odsącz złoty proszek, przemyj 3× wodą destylowaną, przemyj acetonem, wysusz",
      "KROK 9 (wytop): Umieść proszek w tyglu grafitowym, dodaj szczyptę boraksu jako topnik, przetop palnikiem lub piecem (>1064°C)",
      "KROK 10: Platynę i pallad wytrąć z filtratu — Pt przez NH4Cl (wytrąca (NH4)2PtCl6), Pd przez DMAG lub cementację Cu",
    ],
  },
  {
    id: "hno3_dilute",
    name: "Kwas azotowy rozcieńczony (HNO3 25-30%)",
    nameEn: "Dilute Nitric Acid",
    description:
      "Selektywna metoda odzysku srebra i metali pospolitych (Cu, Ni, Pb). Złoto nie reaguje z rozcieńczonym HNO3 i pozostaje w osadzie.",
    targetMetals: ["Ag"],
    reagents: [
      {
        name: "Kwas azotowy rozcieńczony (HNO3 25%)",
        formula: "HNO3",
        concentration: 25,
        amountPerKg: 2.5,
        pricePerLiter: 22.0,
      },
      {
        name: "Chlorek sodu (do wytrącania AgCl)",
        formula: "NaCl",
        concentration: 100,
        amountPerKg: 0.1,
        pricePerLiter: 3.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 60,
    temperatureOptimal: 40,
    timePerKgMin: 2,
    timePerKgMax: 6,
    yieldPercent: { Au: 0, Ag: 85, Pt: 5, Pd: 10 },
    electricityKwhPerKg: 0.2,
    safetyNotes:
      "Wydziela opary NO2/NO (brązowe/bezbarwne). Praca pod wyciągiem. Rękawice kwasoodporne obowiązkowe.",
    steps: [
      "Przygotuj rozcieńczony HNO3 (25-30%) w naczyniu kwasoodpornym",
      "Dodaj wsad elektroniczny do kwasu",
      "Mieszaj i podgrzewaj do 40°C przez 2-4 godziny",
      "Odsącz złoto i platynę pozostałe w osadzie (nereagujące)",
      "Do roztworu dodaj NaCl — wytrąca się AgCl (biały osad)",
      "Odsącz AgCl, przemyj, osusz",
      "Redukuj AgCl do Ag metalicznego: HNO3 + Zn lub elektrolitycznie",
    ],
  },
  {
    id: "hno3_concentrated",
    name: "Kwas azotowy stężony (HNO3 65%)",
    nameEn: "Concentrated Nitric Acid",
    description:
      "Agresywna metoda do wsadów bogatych w miedź i srebro. Stężony HNO3 szybko rozpuszcza metale nieszlachetne, Ag i Pd, pozostawiając Au i Pt.",
    targetMetals: ["Ag", "Pd"],
    reagents: [
      {
        name: "Kwas azotowy stężony (HNO3 65%)",
        formula: "HNO3",
        concentration: 65,
        amountPerKg: 2.0,
        pricePerLiter: 28.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 50,
    temperatureOptimal: 35,
    timePerKgMin: 1,
    timePerKgMax: 4,
    yieldPercent: { Au: 0, Ag: 90, Pt: 0, Pd: 70 },
    electricityKwhPerKg: 0.15,
    safetyNotes:
      "BARDZO NIEBEZPIECZNY. Intensywne opary NOx. Wymagany wyciąg. Reakcja może być gwałtowna — dodawaj wsad bardzo powoli!",
    steps: [
      "Pracuj wyłącznie pod sprawnym wyciągiem",
      "Wlej stężony HNO3 do naczynia kwasoodpornego",
      "Bardzo powoli i stopniowo dodawaj wsad (ryzyko gwałtownej reakcji!)",
      "Utrzymuj temp. 30-40°C — reakcja jest egzotermiczna",
      "Odsącz nierozpuszczony osad (Au, Pt, ceramika)",
      "Do filtratu dodaj NaCl — wytrąca się AgCl",
      "Odsącz i przetwórz AgCl do metalicznego srebra",
    ],
  },
  {
    id: "hcl_h2o2",
    name: "HCl + H2O2 (etching kwasowy)",
    nameEn: "HCl + H2O2 Acid Etching",
    description:
      "Alternatywna metoda dla wody królewskiej. Kwas solny z nadtlenkiem wodoru tworzy chlor in-situ, który rozpuszcza złoto. Bezpieczniejsza alternatywa — bez oparów NOx.",
    targetMetals: ["Au", "Pd"],
    reagents: [
      {
        name: "Kwas solny (HCl)",
        formula: "HCl",
        concentration: 35,
        amountPerKg: 3.0,
        pricePerLiter: 18.0,
      },
      {
        name: "Nadtlenek wodoru (H2O2)",
        formula: "H2O2",
        concentration: 30,
        amountPerKg: 1.5,
        pricePerLiter: 20.0,
      },
      {
        name: "Wodorosiarczyn sodu (reduktor SMB)",
        formula: "NaHSO3",
        concentration: 40,
        amountPerKg: 0.3,
        pricePerLiter: 12.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 60,
    temperatureOptimal: 45,
    timePerKgMin: 6,
    timePerKgMax: 24,
    yieldPercent: { Au: 90, Ag: 15, Pt: 60, Pd: 75 },
    electricityKwhPerKg: 0.3,
    safetyNotes:
      "Brak oparów NOx, ale wydziela chlor (żółtozielony gaz). Praca pod wyciągiem. H2O2 dodawaj ostrożnie — reakcja może być egzotermiczna.",
    steps: [
      "Przygotuj HCl 35% w naczyniu kwasoodpornym",
      "Dodaj wsad elektroniczny",
      "Powoli dodawaj H2O2 (30%) — obserwuj reakcję",
      "Mieszaj regularnie, utrzymuj temp. 40-50°C",
      "Jeśli reakcja zanika, dodaj więcej H2O2 (w małych porcjach)",
      "Filtruj po zakończeniu reakcji (12-24h)",
      "Wytrąć złoto przez dodanie SMB (NaHSO3)",
      "Odsącz, przemyj, wysusz i przetop złoty proszek",
    ],
  },
  {
    id: "nitrate_boat",
    name: "Łódź azotanowa (NaNO3 + H2SO4)",
    nameEn: "Nitrate Boat (NaNO3 + H2SO4)",
    description:
      "Stara metoda rafinacyjna stosowana przez jubilerów. Mieszanina azotanu sodu i kwasu siarkowego tworzy kwas azotowy in-situ. Skuteczna do oczyszczania stopów złota.",
    targetMetals: ["Au", "Ag"],
    reagents: [
      {
        name: "Azotan sodu (NaNO3)",
        formula: "NaNO3",
        concentration: 99,
        amountPerKg: 0.5,
        pricePerLiter: 18.0,
      },
      {
        name: "Kwas siarkowy (H2SO4)",
        formula: "H2SO4",
        concentration: 98,
        amountPerKg: 1.5,
        pricePerLiter: 28.0,
      },
    ],
    temperatureMin: 60,
    temperatureMax: 120,
    temperatureOptimal: 90,
    timePerKgMin: 3,
    timePerKgMax: 8,
    yieldPercent: { Au: 85, Ag: 90, Pt: 30, Pd: 40 },
    electricityKwhPerKg: 0.8,
    safetyNotes:
      "BARDZO WYSOKA TEMPERATURA. H2SO4 jest silnie egzotermiczny z wodą. Opary NOx. Stosuj wyłącznie pod wyciągiem z wyposażeniem ochronnym.",
    steps: [
      "Przygotuj kwas siarkowy (98%) w naczyniu odpornym na temp i kwasy",
      "Stopniowo dodawaj NaNO3 do kwasu (NIE odwrotnie!)",
      "Podgrzewaj do 80-100°C przy ciągłym mieszaniu",
      "Dodaj wsad — złom złota/elektronika",
      "Utrzymuj temperaturę przez 3-6 godzin",
      "Ostudź i rozcieńcz wodą (OSTROŻNIE — silnie egzotermiczne!)",
      "Odsącz nierozpuszczony osad",
      "Wytrąć srebro przez dodanie NaCl (AgCl)",
      "Wytrąć złoto przez SMB lub elektrolitycznie",
    ],
  },
  {
    id: "electrolysis",
    name: "Elektroliza (rafinacja elektrolityczna)",
    nameEn: "Electrolytic Refining",
    description:
      "Najbardziej selektywna metoda rafinacji złota. Złoto z anody przechodzi do katody jako czysty metal 999+. Wymaga wstępnego stopienia wsadu w anodę.",
    targetMetals: ["Au", "Ag"],
    reagents: [
      {
        name: "Kwas azotowy (elektrolit bazowy)",
        formula: "HNO3",
        concentration: 10,
        amountPerKg: 2.0,
        pricePerLiter: 18.0,
      },
      {
        name: "Azotan złota (AuNO3, uzupełniacz)",
        formula: "Au(NO3)3",
        concentration: 5,
        amountPerKg: 0.1,
        pricePerLiter: 1800.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 50,
    temperatureOptimal: 30,
    timePerKgMin: 8,
    timePerKgMax: 48,
    yieldPercent: { Au: 99, Ag: 95, Pt: 60, Pd: 50 },
    electricityKwhPerKg: 2.5,
    safetyNotes:
      "Elektroliza jest stosunkowo bezpieczna. Jednak elektrolit (kwas azotowy) jest żrący. Stosuj rękawice. Wentylacja zalecana.",
    steps: [
      "Przetop wsad w tyglu grafitowym z boraksu — uformuj anodę",
      "Przygotuj wannę elektrolityczną z roztworem HNO3 (10%) + Au(NO3)3",
      "Podłącz anodę (wsad) i katodę (czyste Au lub Ti)",
      "Ustaw napięcie 0.5-1.5V, gęstość prądu 50-200 A/m²",
      "Elektrolizuj 12-48h w zależności od masy wsadu",
      "Złoto osadza się na katodzie jako czysty metal 999+",
      "Zbierz szlam anodowy (Pt, Pd, Ag, inne) do dalszej obróbki",
      "Przetop katodę — gotowe czyste złoto",
    ],
  },
  {
    id: "wohlwill_process",
    name: "Proces Wöhlwilla (rafinacja złota 999.9)",
    nameEn: "Wohlwill Process",
    description:
      "Przemysłowy proces elektrolityczny dla złota najwyższej czystości (999.9). Elektrolit na bazie chlorku złota (AuCl3) w HCl. Standard dla mennic i rafinerii.",
    targetMetals: ["Au"],
    reagents: [
      {
        name: "Kwas solny (elektrolit)",
        formula: "HCl",
        concentration: 20,
        amountPerKg: 3.0,
        pricePerLiter: 12.0,
      },
      {
        name: "Chlorek złota (AuCl3, elektrolit)",
        formula: "AuCl3",
        concentration: 10,
        amountPerKg: 0.2,
        pricePerLiter: 3200.0,
      },
    ],
    temperatureMin: 60,
    temperatureMax: 75,
    temperatureOptimal: 70,
    timePerKgMin: 24,
    timePerKgMax: 72,
    yieldPercent: { Au: 99.5, Ag: 0, Pt: 30, Pd: 20 },
    electricityKwhPerKg: 3.0,
    safetyNotes:
      "Wysoka temperatura elektrolitu. HCl opary kwasowe. Wyciąg obowiązkowy. Koszt AuCl3 jest znaczący — opłacalny tylko dla dużych wsadów.",
    steps: [
      "Przygotuj anody przez stopienie wsadu z Au (min. 90% Au)",
      "Przygotuj elektrolit: HCl 20% + AuCl3 10% + woda, T=65°C",
      "Zamontuj anody i katody (folia tytanowa)",
      "Ustaw parametry: U=1.2V, gęstość prądu 500-1000 A/m², T=65-70°C",
      "Elektrolizuj 24-72h — złoto osadza się na katodach",
      "Pobierz katody, oczyść z elektrolitu, przetop",
      "Wynik: złoto 999.9 czystości",
    ],
  },
  {
    id: "miller_process",
    name: "Proces Millera (chloracja)",
    nameEn: "Miller Process (Chlorination)",
    category: "pyrometallurgical",
    description:
      "Przemysłowa metoda oczyszczania złota przez nadmuch chloru do stopionego metalu. Zanieczyszczenia tworzą chlorki, złoto pozostaje czyste (999+). Szybki i wydajny. UWAGA: Proces pirometalurgiczny wymagający pieca indukcyjnego.",
    targetMetals: ["Au"],
    reagents: [
      {
        name: "Chlor gazowy (Cl2)",
        formula: "Cl2",
        concentration: 99,
        amountPerKg: 0.5,
        pricePerLiter: 38.0,
      },
      {
        name: "Boraks (topnik)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.3,
        pricePerLiter: 10.0,
      },
    ],
    temperatureMin: 1064,
    temperatureMax: 1200,
    temperatureOptimal: 1100,
    timePerKgMin: 0.5,
    timePerKgMax: 2,
    yieldPercent: { Au: 98, Ag: 0, Pt: 20, Pd: 10 },
    electricityKwhPerKg: 5.0,
    safetyNotes:
      "BARDZO NIEBEZPIECZNY — chlor gazowy jest silnie toksyczny. Wymagany szczelny system z neutralizacją NaOH. Tylko dla profesjonalnych rafinerii z odpowiednim wyposażeniem.",
    steps: [
      "Przetop wsad w piecu indukcyjnym do 1100°C",
      "Dodaj boraks jako topnik",
      "Wdmuchuj Cl2 przez rurę z glinki/kwarcu do stopionego metalu",
      "Chlor reaguje z zanieczyszczeniami tworząc chlorki (pływają na powierzchni)",
      "Kontynuuj do zaniku żółtego płomienia AgCl",
      "Zatrzymaj dopływ Cl2, spuść złocisty metal do form",
      "Wynik: złoto 99.0-99.5% (do dalszej rafinacji Wöhlwilla lub sprzedaży)",
    ],
  },
  {
    id: "cementation_zinc",
    name: "Cementacja cynkiem (wytrącanie Au)",
    nameEn: "Zinc Cementation",
    description:
      "Klasyczna metoda wytrącania złota z roztworu (np. cyjanku) przez dodanie cynku. Cynk wypiera złoto z roztworu. Stosowana jako krok wytrącania po ługowaniu.",
    targetMetals: ["Au", "Ag"],
    reagents: [
      {
        name: "Cynk metaliczny (granulki)",
        formula: "Zn",
        concentration: 99,
        amountPerKg: 0.4,
        pricePerLiter: 65.0,
      },
      {
        name: "Ług cyjanku sodu (NaCN, opcjonalny)",
        formula: "NaCN",
        concentration: 5,
        amountPerKg: 1.0,
        pricePerLiter: 40.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 60,
    temperatureOptimal: 40,
    timePerKgMin: 2,
    timePerKgMax: 8,
    yieldPercent: { Au: 80, Ag: 75, Pt: 20, Pd: 30 },
    electricityKwhPerKg: 0.1,
    safetyNotes:
      "UWAGA przy NaCN — cyjanki są silnie toksyczne! Pracuj przy pH > 10 (zasadowe), nigdy z kwasem (wydzielanie HCN!). Cynk bez cyjanku jest bezpieczny.",
    steps: [
      "Przygotuj roztwór zawierający złoto (np. po ługowaniu cyjankowym)",
      "Doprowadź pH do 10-12 (alkaliczne) — KRYTYCZNE przy NaCN",
      "Dodaj granulki cynku do roztworu",
      "Mieszaj przez 2-4h — złoto osadza się na cynku",
      "Odsącz osad (złoto + cynk)",
      "Rozpuść cynk w rozcieńczonym H2SO4 (lub HCl) — złoto pozostaje",
      "Odsącz złoty proszek, przemyj, wysusz i przetop",
    ],
  },
];

router.get("/chemicals/processes", (_req, res) => {
  res.json(chemicalProcesses);
});

export default router;
