import { Router, type IRouter } from "express";

const router: IRouter = Router();

const PREP_STEPS_ELECTRONIC = [
  "Demontaż mechaniczny: usuń śruby, obudowy plastikowe, złącza wtykowe i duże kondensatory elektrolityczne (typ. zmniejsza masę wsadu o 20-40%)",
  "Separacja materiałów: odseparuj elementy plastikowe i ceramiczne (selekcja wzrokowa), ferromagnetyki magnesem trwałym — nie reagują z kwasami i utrudniają filtrację",
  "Rozdrobnienie wsadu: pociąć płytki na kawałki < 2 cm nożycami do blachy lub granulatorem — krytyczne dla szybkości i kompletności reakcji kwasowej",
];

const PREP_STEPS_METAL = [
  "Weryfikacja wsadu: sprawdź skład stopu (wymagane min. 90% Au) — użyj kamienia probierczego, spektrometru XRF lub analizy chemicznej",
  "Wytop wstępny: jeśli wsad jest proszkiem lub złomem, przetop w tyglu grafitowym z boraksem i odlej na wstępne ingoty/anody",
  "Przygotowanie instalacji: sprawdź wyposażenie elektryczne/gazowe, skalibruj mierniki, przygotuj komplet odczynników i naczynie robocze",
];

const PREP_STEPS_SOLUTION = [
  "Weryfikacja roztworu: sprawdź zawartość Au/Ag w roztworze wejściowym (np. po ługowaniu cyjankowym lub filtracie HNO3)",
  "Regulacja pH: doprowadź pH do 10-12 dodając Ca(OH)2 lub NaOH — KRYTYCZNE przy NaCN (poniżej pH 10 powstaje śmiertelny HCN!)",
  "Przygotowanie granulat Zn: opłucz granulki rozcieńczonym kwasem (usuwa tlenki), przemyj wodą destylowaną, przygotuj pojemnik filtracyjny",
];

const chemicalProcesses = [
  {
    id: "aqua_regia",
    name: "Woda Królewska (HCl + HNO3)",
    nameEn: "Aqua Regia",
    description:
      "Klasyczna metoda odzysku Au, Ag i platynowców z e-odpadów. Proces dwuetapowy: (1) Pre-trawienie HNO3 25% — usuwa Cu, Ni, Pb, Sn i rozpuszcza Ag; filtrat HNO3 zachować do odzysku Ag (~80% uzysku) przez strącenie NaCl→AgCl i redukcję. (2) Woda królewska HCl:HNO3 3:1 — rozpuszcza Au, Pt, Pd z oczyszczonego osadu. Pominięcie odzysku Ag z filtratu HNO3 to utrata ~80% całego Ag w wsadzie.",
    targetMetals: ["Au", "Ag", "Pt", "Pd"],
    outputPurityText: "Au: 95–99% (surowy proszek) → wymaga rafinacji elektrolitycznej do 999; Ag: ~80% odzysku — ze stepu pre-trawienia HNO3 (filtrat) + AgCl po etapie AR; Pt/Pd: 40–60% surowego strątu — wymagana dalsza separacja",
    reagents: [
      {
        name: "Kwas azotowy rozcieńczony — pre-trawienie (HNO3 25%)",
        formula: "HNO3",
        concentration: 25,
        availableConcentrations: [20, 25, 30, 35, 45, 50],
        amountPerKg: 1.5,
        pricePerLiter: 22.0,
      },
      {
        name: "Kwas solny (HCl)",
        formula: "HCl",
        concentration: 35,
        availableConcentrations: [25, 30, 33, 35, 37],
        amountPerKg: 1.0,
        pricePerLiter: 18.0,
      },
      {
        name: "Kwas azotowy stężony (HNO3 65%)",
        formula: "HNO3",
        concentration: 65,
        availableConcentrations: [50, 55, 60, 65, 68],
        amountPerKg: 0.33,
        pricePerLiter: 28.0,
      },
      {
        name: "Mocznik (rozkład nadmiaru HNO3)",
        formula: "CO(NH2)2",
        concentration: 99,
        amountPerKg: 0.05,
        pricePerLiter: 4.0,
      },
      {
        name: "Wodorosiarczyn sodu — reduktor SMB (wytrącanie Au)",
        formula: "NaHSO3",
        concentration: 40,
        availableConcentrations: [35, 40, 45],
        amountPerKg: 0.03,
        pricePerLiter: 12.0,
      },
      {
        name: "Boraks (topnik do wytopu)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.005,
        pricePerLiter: 10.0,
      },
    ],
    temperatureMin: 50,
    temperatureMax: 90,
    temperatureOptimal: 70,
    timePerKgMin: 4,
    timePerKgMax: 10,
    yieldPercent: { Au: 95, Ag: 80, Pt: 85, Pd: 80 },
    electricityKwhPerKg: 0.6,
    safetyNotes:
      "UWAGA: Wydziela trujące opary NOx i HCl. Praca WYŁĄCZNIE pod sprawnym wyciągiem z aktywnym węglem. Wyposażenie: maska z filtrem ABEK P3, rękawice kwasoodporne (nitril/neopren), fartuch kwasoodporny, gogle ochronne. Nigdy nie wlewaj wody do stężonego kwasu!",
    steps: [
      ...PREP_STEPS_ELECTRONIC,
      "BHP: sprawdź wyciąg, załóż maskę ABEK P3, rękawice kwasoodporne i gogle przed rozpoczęciem",
      "Pre-trawienie HNO3: rozdrobniony wsad zalej HNO3 25% (~1500 ml/kg wsadu aktywnego), podgrzej do 40–50°C przez 2-4h — usuwa Cu, Ni, Pb, Fe, Sn; HNO3 jest KONIECZNY przed wodą królewską",
      "Odsącz i przemyj osad (Au, Pt, Pd, AgCl, ceramika) wodą destylowaną — filtrat z HNO3 zachowaj do odzysku Ag i Cu",
      "Woda królewska: przygotuj mieszaninę HCl 35% + HNO3 65% w proporcji 3:1 (obj.) w naczyniu PTFE lub szkle borokrzemowym",
      "Powoli wsypuj osad do wody królewskiej, podgrzewaj do 60-70°C mieszając co 30 min — Au, Pt, Pd przechodzą do roztworu",
      "Po rozpuszczeniu (4-8h) odsącz ceramikę i AgCl — AgCl odłóż do dalszego odzysku srebra",
      "Rozkład HNO3: dodaj mocznik CO(NH2)2 porcjami (1-2 g/100 ml) aż ustąpią bąbelki — niszczy nadmiar HNO3 przeszkadzający redukcji",
      "Wytrącanie Au: powoli dodawaj SMB (NaHSO3) do zimnego roztworu — złoto wytrąca się jako brązowy proszek",
      "Odsącz złoty proszek, przemyj 3× wodą destylowaną, przemyj acetonem, wysusz",
      "Wytop: umieść proszek w tyglu grafitowym, dodaj szczyptę boraksu jako topnik, przetop palnikiem lub piecem (>1064°C)",
      "Platynę i pallad wytrąć z filtratu — Pt przez NH4Cl (wytrąca (NH4)2PtCl6), Pd przez DMAG lub cementację Cu",
    ],
  },
  {
    id: "hno3_dilute",
    name: "Kwas azotowy rozcieńczony (HNO3 25-30%)",
    nameEn: "Dilute Nitric Acid",
    description:
      "Selektywna metoda odzysku srebra i metali pospolitych (Cu, Ni, Pb). Złoto nie reaguje z rozcieńczonym HNO3 i pozostaje w osadzie jako cenny produkt do dalszej obróbki wodą królewską.",
    targetMetals: ["Ag"],
    outputPurityText: "Ag: 90–95% (po redukcji Zn) — odpowiada próbie 900–950; osad (Au, Pt) do dalszej obróbki wodą królewską",
    reagents: [
      {
        name: "Kwas azotowy rozcieńczony (HNO3 25%)",
        formula: "HNO3",
        concentration: 25,
        availableConcentrations: [20, 25, 30, 35, 45, 50],
        amountPerKg: 1.2,
        pricePerLiter: 22.0,
      },
      {
        name: "Chlorek sodu (wytrącanie AgCl)",
        formula: "NaCl",
        concentration: 100,
        amountPerKg: 0.02,
        pricePerLiter: 3.0,
      },
      {
        name: "Cynk metaliczny — redukcja AgCl→Ag",
        formula: "Zn",
        concentration: 99,
        amountPerKg: 0.005,
        pricePerLiter: 65.0,
      },
      {
        name: "Kwas solny HCl — rozpuszczenie cynku z osadu",
        formula: "HCl",
        concentration: 35,
        availableConcentrations: [25, 30, 33, 35, 37],
        amountPerKg: 0.08,
        pricePerLiter: 18.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 60,
    temperatureOptimal: 40,
    timePerKgMin: 2,
    timePerKgMax: 6,
    yieldPercent: { Au: 0, Ag: 85, Pt: 5, Pd: 10 },
    electricityKwhPerKg: 0.2,
    safetyNotes:
      "Wydziela opary NO2/NO (brunatne/bezbarwne). Praca pod wyciągiem. Rękawice kwasoodporne obowiązkowe. Uwaga przy etapie HCl — wydziela gaz H2 przy kontakcie z cynkiem (brak iskier!).",
    steps: [
      ...PREP_STEPS_ELECTRONIC,
      "BHP: wyciąg, rękawice kwasoodporne, gogle ochronne",
      "Przygotuj HNO3 25% w naczyniu kwasoodpornym (~1200 ml/kg wsadu aktywnego — ilość krytyczna dla pełnego rozpuszczenia Cu/Ag/Ni)",
      "Dodaj wsad elektroniczny porcjami — obserwuj intensywność reakcji (brunatne opary NO2)",
      "Mieszaj i podgrzewaj do 40°C przez 2-4h — Cu, Ag, Ni, Pb przechodzą do roztworu",
      "Odsącz osad (Au, Pt, ceramika) — cenny wsad do dalszego procesu wody królewskiej",
      "Wytrącanie Ag: do filtratu dodaj NaCl — wytrąca się AgCl (biały osad)",
      "Odsącz AgCl, przemyj 3× wodą destylowaną, osusz",
      "Redukcja AgCl→Ag: umieść AgCl w naczyniu, dodaj granulki Zn i przykryj wodą — Zn wypiera Ag z AgCl",
      "Poczekaj 30-60 min — odsącz szary proszek Ag + resztki Zn",
      "Dodaj rozcieńczony HCl — dissolwuje Zn, Ag pozostaje; odsącz, przemyj, wysusz proszek Ag",
      "Przetop proszek Ag w tyglu — gotowe metaliczne srebro",
    ],
  },
  {
    id: "hno3_concentrated",
    name: "Kwas azotowy stężony (HNO3 65%)",
    nameEn: "Concentrated Nitric Acid",
    description:
      "Agresywna metoda do wsadów bogatych w miedź i srebro. Stężony HNO3 szybko rozpuszcza metale nieszlachetne, Ag i Pd, pozostawiając Au i Pt w osadzie. Wymaga NaCl do wytrącenia AgCl i cynku do redukcji srebra metalicznego.",
    targetMetals: ["Ag", "Pd"],
    outputPurityText: "Ag: 92–97% (po redukcji Zn) — odpowiada próbie 920–970; Pd: 70–85% surowy (wymaga dalszego oczyszczenia)",
    reagents: [
      {
        name: "Kwas azotowy stężony (HNO3 65%)",
        formula: "HNO3",
        concentration: 65,
        availableConcentrations: [50, 55, 60, 65, 68],
        amountPerKg: 0.6,
        pricePerLiter: 28.0,
      },
      {
        name: "Chlorek sodu (wytrącanie AgCl)",
        formula: "NaCl",
        concentration: 100,
        amountPerKg: 0.01,
        pricePerLiter: 3.0,
      },
      {
        name: "Cynk metaliczny — redukcja AgCl→Ag",
        formula: "Zn",
        concentration: 99,
        amountPerKg: 0.005,
        pricePerLiter: 65.0,
      },
      {
        name: "Kwas solny HCl — rozpuszczenie cynku z osadu",
        formula: "HCl",
        concentration: 35,
        availableConcentrations: [25, 30, 33, 35, 37],
        amountPerKg: 0.05,
        pricePerLiter: 18.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 50,
    temperatureOptimal: 35,
    timePerKgMin: 1,
    timePerKgMax: 4,
    yieldPercent: { Au: 0, Ag: 90, Pt: 0, Pd: 70 },
    electricityKwhPerKg: 0.15,
    safetyNotes:
      "BARDZO NIEBEZPIECZNY. Intensywne opary NOx (brunatny dym). Wymagany sprawny wyciąg z aktywnym węglem. Maska ABEK P3, rękawice kwasoodporne, gogle. Reakcja gwałtowna — dodawaj wsad bardzo powoli i małymi porcjami!",
    steps: [
      ...PREP_STEPS_ELECTRONIC,
      "BHP: wyciąg aktywny z węglem, maska ABEK P3, rękawice kwasoodporne, gogle",
      "Wlej stężony HNO3 65% do naczynia kwasoodpornego (PTFE lub szkło borokrzemowe)",
      "Wsad dodawaj BARDZO powoli porcjami — reakcja jest gwałtowna, intensywne brunatne opary NOx",
      "Utrzymuj temperaturę 30-40°C (reakcja egzotermiczna — chłodź w razie potrzeby)",
      "Kontynuuj do zaniku intensywnych oparów (1-3h na kg wsadu)",
      "Odsącz osad (Au, Pt, ceramika) — zachowaj do dalszej obróbki wodą królewską",
      "Wytrącanie Ag: do filtratu dodaj NaCl — wytrąca się AgCl (biały osad)",
      "Odsącz AgCl, przemyj 3× wodą destylowaną, osusz",
      "Redukcja AgCl→Ag: dodaj granulki Zn do zawiesiny AgCl z wodą — Zn wypiera Ag",
      "Po 30-60 min odsącz szary proszek Ag+Zn; dodaj HCl — dissolwuje Zn, Ag pozostaje",
      "Odsącz i przemyj proszek Ag, przetop w tyglu — gotowe metaliczne srebro",
    ],
  },
  {
    id: "hcl_h2o2",
    name: "HCl + H2O2 (etching kwasowy)",
    nameEn: "HCl + H2O2 Acid Etching",
    description:
      "Alternatywna metoda dla wody królewskiej. Kwas solny z nadtlenkiem wodoru tworzy chlor in-situ, który rozpuszcza złoto. Bezpieczniejsza alternatywa — bez oparów NOx. Na koniec złoty proszek przetapiany z boraksem.",
    targetMetals: ["Au", "Pd"],
    outputPurityText: "Au: 95–98% (surowy proszek po SMB) — odpowiada próbie 950–980; wymaga rafinacji elektrolitycznej do 999; Pd: 50–70% surowy",
    reagents: [
      {
        name: "Kwas solny (HCl)",
        formula: "HCl",
        concentration: 35,
        availableConcentrations: [25, 30, 33, 35, 37],
        amountPerKg: 0.5,
        pricePerLiter: 18.0,
      },
      {
        name: "Nadtlenek wodoru (H2O2)",
        formula: "H2O2",
        concentration: 30,
        availableConcentrations: [3, 15, 30, 35],
        amountPerKg: 0.2,
        pricePerLiter: 20.0,
      },
      {
        name: "Wodorosiarczyn sodu — reduktor SMB (wytrącanie Au)",
        formula: "NaHSO3",
        concentration: 40,
        availableConcentrations: [35, 40, 45],
        amountPerKg: 0.02,
        pricePerLiter: 12.0,
      },
      {
        name: "Boraks (topnik do wytopu Au)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.005,
        pricePerLiter: 10.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 60,
    temperatureOptimal: 45,
    timePerKgMin: 6,
    timePerKgMax: 16,
    yieldPercent: { Au: 90, Ag: 15, Pt: 60, Pd: 75 },
    electricityKwhPerKg: 0.3,
    safetyNotes:
      "Brak oparów NOx, ale wydziela chlor gazowy (żółtozielony). Praca pod wyciągiem. Rękawice kwasoodporne, gogle. H2O2 dodawaj bardzo ostrożnie — reakcja egzotermiczna; nigdy nie dodawaj dużej porcji naraz.",
    steps: [
      ...PREP_STEPS_ELECTRONIC,
      "BHP: wyciąg (chlor!), rękawice kwasoodporne, gogle ochronne",
      "Wlej HCl 35% do naczynia kwasoodpornego (PTFE lub szkło)",
      "Dodaj rozdrobniony wsad elektroniczny",
      "Bardzo powoli, porcjami po 10-20 ml, dodawaj H2O2 30% — pojawi się chlor, reakcja jest egzotermiczna",
      "Mieszaj regularnie, utrzymuj temp. 40-50°C; dodawaj H2O2, gdy reakcja zwalnia",
      "Po 12-24h filtruj — ceramika i nierozpuszczony osad zostają na filtrze",
      "Wytrącanie Au: ochłodź roztwór; powoli dodawaj SMB (NaHSO3) — brązowy proszek Au wytrąca się",
      "Odsącz złoto, przemyj 3× wodą destylowaną, przemyj acetonem, wysusz",
      "Wytop proszek Au w tyglu grafitowym ze szczyptą boraksu jako topnikiem (>1064°C)",
    ],
  },
  {
    id: "nitrate_boat",
    name: "Łódź azotanowa (NaNO3 + H2SO4)",
    nameEn: "Nitrate Boat (NaNO3 + H2SO4)",
    description:
      "Stara metoda rafinacyjna stosowana przez jubilerów. Mieszanina azotanu sodu i kwasu siarkowego tworzy kwas azotowy in-situ. Skuteczna do oczyszczania stopów złota. Wymaga NaCl do wytrącenia Ag i SMB do wytrącenia Au z roztworu.",
    targetMetals: ["Au", "Ag"],
    outputPurityText: "Au: 85–92% surowy (wymaga dalszej rafinacji elektrolitycznej); Ag: 90–95% (surowy AgCl po wytrąceniu NaCl)",
    reagents: [
      {
        name: "Azotan sodu (NaNO3)",
        formula: "NaNO3",
        concentration: 99,
        amountPerKg: 0.20,
        pricePerLiter: 18.0,
      },
      {
        name: "Kwas siarkowy (H2SO4)",
        formula: "H2SO4",
        concentration: 98,
        availableConcentrations: [50, 70, 80, 96, 98],
        amountPerKg: 0.3,
        pricePerLiter: 28.0,
      },
      {
        name: "Chlorek sodu (wytrącanie AgCl)",
        formula: "NaCl",
        concentration: 100,
        amountPerKg: 0.01,
        pricePerLiter: 3.0,
      },
      {
        name: "Wodorosiarczyn sodu — SMB (wytrącanie Au)",
        formula: "NaHSO3",
        concentration: 40,
        availableConcentrations: [35, 40, 45],
        amountPerKg: 0.05,
        pricePerLiter: 12.0,
      },
    ],
    temperatureMin: 60,
    temperatureMax: 120,
    temperatureOptimal: 90,
    timePerKgMin: 3,
    timePerKgMax: 8,
    yieldPercent: { Au: 85, Ag: 90, Pt: 30, Pd: 40 },
    electricityKwhPerKg: 0.8,
    safetyNotes:
      "BARDZO WYSOKA TEMPERATURA + opary NOx. H2SO4 98% jest silnie egzotermiczny z wodą — nigdy nie dodawaj wody do stężonego H2SO4! Maska ABEK P3, rękawice kwasoodporne termooodporne (neopren), fartuch, gogle. Wyciąg obowiązkowy.",
    steps: [
      ...PREP_STEPS_ELECTRONIC,
      "BHP: wyciąg z aktywnym węglem, maska ABEK P3, rękawice termooodporne i kwasoodporne, gogle",
      "Wlej H2SO4 98% do naczynia żaroodpornego i kwasoodpornego (kwarc lub niobian)",
      "Stopniowo dodawaj NaNO3 do kwasu — NIE odwrotnie! Mieszaj do rozpuszczenia",
      "Podgrzewaj do 80-100°C przy ciągłym mieszaniu — tworzy się HNO3 in-situ",
      "Dodaj rozdrobniony wsad elektroniczny porcjami",
      "Utrzymuj temperaturę 80-100°C przez 3-6h — metale przechodzą do roztworu",
      "Ostudź do pokojowej; ostrożnie rozcieńcz wodą (SILNIE EGZOTERMICZNE — dodawaj wodę DO kwasu, nie odwrotnie!)",
      "Wytrącanie Ag: do filtratu dodaj NaCl — biały osad AgCl; odsącz, przemyj, osusz",
      "Wytrącanie Au: do filtratu bez AgCl dodaj SMB (NaHSO3) — brązowy proszek Au wytrąca się",
      "Odsącz złoto, przemyj, wysusz i przetop w tyglu grafitowym",
    ],
  },
  {
    id: "electrolysis",
    name: "Elektroliza (rafinacja elektrolityczna)",
    nameEn: "Electrolytic Refining",
    description:
      "Selektywna metoda rafinacji złota. Złoto z anody przechodzi do katody jako czysty metal 999+. Wymaga wstępnego stopienia wsadu w anodę (z boraksem jako topnikiem). Elektrolit: HNO3 10% + Au(NO3)3.",
    targetMetals: ["Au", "Ag"],
    outputPurityText: "Au: 999+ (99.9%) — gotowe do sprzedaży jako złoto inwestycyjne; Ag: 95–98% (szlam anodowy wymaga dalszej obróbki)",
    reagents: [
      {
        name: "Kwas azotowy (elektrolit bazowy)",
        formula: "HNO3",
        concentration: 10,
        availableConcentrations: [5, 8, 10, 12, 15, 20],
        amountPerKg: 0.5,
        pricePerLiter: 18.0,
      },
      {
        name: "Azotan złota (Au(NO3)3, uzupełniacz elektrolitu)",
        formula: "Au(NO3)3",
        concentration: 5,
        amountPerKg: 0.025,
        pricePerLiter: 1800.0,
      },
      {
        name: "Boraks (topnik do wytopu anody)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.05,
        pricePerLiter: 10.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 50,
    temperatureOptimal: 30,
    timePerKgMin: 8,
    timePerKgMax: 24,
    yieldPercent: { Au: 99, Ag: 95, Pt: 60, Pd: 50 },
    electricityKwhPerKg: 2.5,
    safetyNotes:
      "Elektroliza sama w sobie jest stosunkowo bezpieczna. Jednak elektrolit (HNO3 10%) jest żrący — rękawice nitrylowe i gogle. Etap wytopu anody wymaga palnika (>1064°C) — środki ochrony p.poż.",
    steps: [
      ...PREP_STEPS_METAL,
      "BHP: rękawice nitrylowe, gogle; przy wytociu anody — osłona termiczna i rękawice żaroodporne",
      "Wytop anody: przetop wsad w tyglu grafitowym z boraksem jako topnikiem — uformuj anodę (blok lub płytka)",
      "Przygotuj elektrolit: HNO3 10% + Au(NO3)3 w wannie elektrolitycznej, podgrzej do 25-30°C",
      "Zamontuj anodę (wsad) i katodę (folia tytanowa lub czyste Au)",
      "Ustaw napięcie 0.5-1.5V, gęstość prądu 50-200 A/m²",
      "Elektrolizuj 12-48h — złoto osadza się na katodzie jako czysty metal 999+",
      "Regularnie zbieraj szlam anodowy (Pt, Pd, Ag, inne) do dalszej obróbki",
      "Wyjmij katodę, oczyść z elektrolitu, przemyj wodą destylowaną, przetop",
      "Wynik: złoto 999+ czystości; szlam anodowy przetworzyć wodą królewską lub procesem Wöhlwilla",
    ],
  },
  {
    id: "wohlwill_process",
    name: "Proces Wöhlwilla (rafinacja złota 999.9)",
    nameEn: "Wohlwill Process",
    description:
      "Przemysłowy proces elektrolityczny dla złota najwyższej czystości (999.9). Elektrolit na bazie chlorku złota (AuCl3) w HCl. Standard dla mennic i rafinerii. Wymaga wstępnego wytopu anod z boraksem jako topnikiem.",
    targetMetals: ["Au"],
    outputPurityText: "Au: 999.9 (99.99%) — najwyższa możliwa czystość komercyjna; standard mennic i rynku inwestycyjnego (złoto lokacyjne)",
    reagents: [
      {
        name: "Kwas solny (elektrolit bazowy HCl 20%)",
        formula: "HCl",
        concentration: 20,
        availableConcentrations: [15, 20, 25, 30],
        amountPerKg: 1.0,
        pricePerLiter: 12.0,
      },
      {
        name: "Chlorek złota (AuCl3, uzupełniacz elektrolitu)",
        formula: "AuCl3",
        concentration: 10,
        amountPerKg: 0.05,
        pricePerLiter: 3200.0,
      },
      {
        name: "Boraks (topnik do wytopu anod)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.02,
        pricePerLiter: 10.0,
      },
    ],
    temperatureMin: 60,
    temperatureMax: 75,
    temperatureOptimal: 70,
    timePerKgMin: 24,
    timePerKgMax: 48,
    yieldPercent: { Au: 99.5, Ag: 0, Pt: 30, Pd: 20 },
    electricityKwhPerKg: 3.0,
    safetyNotes:
      "Wysoka temperatura elektrolitu (65-70°C). Opary HCl — wyciąg obowiązkowy. Rękawice kwasoodporne, gogle. Etap wytopu anod wymaga palnika (>1064°C) — osłona termiczna. Koszt AuCl3 bardzo wysoki — opłacalny tylko dla wsadów z >90% Au.",
    steps: [
      ...PREP_STEPS_METAL,
      "BHP: wyciąg aktywny (opary HCl), rękawice kwasoodporne, gogle; przy wytocie anod — osłona termiczna",
      "Wytop anod: przetop wsad (min. 90% Au) w tyglu grafitowym z boraksem — uformuj anody (płytki ~5-10mm)",
      "Przygotuj elektrolit: HCl 20% + AuCl3 10% w wannie kwasoodpornej, podgrzej do 65-70°C",
      "Zamontuj anody i katody (folia tytanowa lub czyste Au)",
      "Ustaw parametry: U=1.0-1.2V, gęstość prądu 500-1000 A/m², T=65-70°C",
      "Elektrolizuj 24-72h — złoto 999.9 osadza się na katodach jako kryształy",
      "Pobierz katody, oczyść z elektrolitu wodą destylowaną, osusz",
      "Przetop katody w tyglu grafitowym — gotowe złoto 999.9",
      "Szlam anodowy (Pt, Pd, Ag) przetworzyć oddzielnie (kwas azotowy lub woda królewska)",
    ],
  },
  {
    id: "miller_process",
    name: "Proces Millera (chloracja pirometalurgiczna)",
    nameEn: "Miller Process (Chlorination)",
    category: "pyrometallurgical",
    description:
      "Przemysłowa metoda oczyszczania złota przez nadmuch chloru do stopionego metalu w piecu indukcyjnym. Zanieczyszczenia (Ag, Cu, Pb, Zn) reagują z Cl2, tworząc chlorki które pływają na powierzchni. Złoto pozostaje czyste (99.0-99.5%). WYMAGA instalacji neutralizacji Cl2 (NaOH).",
    targetMetals: ["Au"],
    outputPurityText: "Au: 990–995 (99.0–99.5%) — produkt pośredni; wymaga rafinacji Wöhlwilla do 999.9 dla rynku inwestycyjnego",
    reagents: [
      {
        name: "Chlor gazowy (Cl2)",
        formula: "Cl2",
        concentration: 99,
        amountPerKg: 0.15,
        pricePerLiter: 38.0,
      },
      {
        name: "Boraks (topnik)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.1,
        pricePerLiter: 10.0,
      },
      {
        name: "Wodorotlenek sodu NaOH 30% (neutralizacja Cl2 w off-gazie)",
        formula: "NaOH",
        concentration: 30,
        availableConcentrations: [10, 20, 25, 30, 40, 50],
        amountPerKg: 0.3,
        pricePerLiter: 8.0,
      },
    ],
    temperatureMin: 1064,
    temperatureMax: 1200,
    temperatureOptimal: 1100,
    timePerKgMin: 0.5,
    timePerKgMax: 2,
    yieldPercent: { Au: 98, Ag: 0, Pt: 20, Pd: 10 },
    electricityKwhPerKg: 5.0,
    safetyNotes:
      "EKSTREMALNIE NIEBEZPIECZNY — chlor gazowy jest silnie toksyczny (LC50=430 mg/m³). WYMAGANY szczelny system z pełną instalacją scrubberową NaOH. Tylko dla profesjonalnych rafinerii z certyfikowanym wyposażeniem, systemem wentylacji i szkolonym personelem. NIE dla amatorów.",
    steps: [
      ...PREP_STEPS_METAL,
      "BHP: certyfikowany scrubber Cl2 z NaOH, maska z filtrem B2P3 lub aparat powietrzny, kombinezon kwasoodporny, wyciąg przemysłowy — MINIMUM",
      "Uruchom piec indukcyjny, nagrzej tygiel grafitowy do 1100°C",
      "Dodaj wsad (stop złota) i boraks jako topnik — poczekaj do pełnego stopienia",
      "Podłącz instalację Cl2 (rura kwarc/glinka) — sprawdź szczelność systemu scrubberowego NaOH",
      "Wdmuchuj Cl2 powoli do stopionego metalu — obserwuj kolor płomienia (żółty = AgCl, biały = PbCl2/ZnCl2)",
      "Off-gaz Cl2 przechodzi przez scrubber NaOH — sprawdzaj pochłanianie papierkiem lakmusowym",
      "Kontynuuj do zaniku barwnych płomieni i klarowania stopionego złota (0.5-2h)",
      "Zatrzymaj dopływ Cl2, spuść złocisty metal do form — wynik: Au 99.0-99.5%",
      "Chlorki z powierzchni (szlam) przetworzyć do odzysku Ag — zawierają AgCl",
    ],
  },
  {
    id: "cementation_zinc",
    name: "Cementacja cynkiem (wytrącanie Au)",
    nameEn: "Zinc Cementation",
    description:
      "Klasyczna metoda wytrącania złota z roztworu (np. cyjanku lub chlorku) przez dodanie cynku. Cynk wypiera złoto z roztworu — cementacja. Po cementacji cynk rozpuszcza się w HCl, a złoto pozostaje jako proszek.",
    targetMetals: ["Au", "Ag"],
    outputPurityText: "Au/Ag: 80–90% (surowy stop Au+Ag po wytopu) — wymaga dalszej rafinacji elektrolitycznej lub procesem Millera",
    reagents: [
      {
        name: "Cynk metaliczny (granulki Zn)",
        formula: "Zn",
        concentration: 99,
        amountPerKg: 0.1,
        pricePerLiter: 65.0,
      },
      {
        name: "Ług cyjanku sodu (NaCN, opcjonalny — do ługowania)",
        formula: "NaCN",
        concentration: 5,
        availableConcentrations: [2, 5, 8, 10, 15, 20],
        amountPerKg: 0.3,
        pricePerLiter: 40.0,
      },
      {
        name: "Kwas solny HCl (rozpuszczenie cynku z osadu Au+Zn)",
        formula: "HCl",
        concentration: 35,
        availableConcentrations: [25, 30, 33, 35, 37],
        amountPerKg: 0.1,
        pricePerLiter: 18.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 60,
    temperatureOptimal: 40,
    timePerKgMin: 3,
    timePerKgMax: 6,
    yieldPercent: { Au: 80, Ag: 75, Pt: 20, Pd: 30 },
    electricityKwhPerKg: 0.1,
    safetyNotes:
      "KRYTYCZNE przy NaCN — cyjanki są silnie toksyczne (śmiertelne)! Pracuj ZAWSZE przy pH > 10 (zasadowe). Nigdy nie mieszaj NaCN z kwasem (wydzielanie HCN!). Etap HCl do cynku jest bezpieczny, ale wydziela H2 — iskry niedopuszczalne.",
    steps: [
      ...PREP_STEPS_SOLUTION,
      "BHP: przy NaCN — maska z filtrem B2P3, rękawice nitrylowe, wyciąg; antidotum (Na2S2O3) i apteczka pod ręką",
      "Dodaj granulki cynku (Zn) do alkalicznego roztworu Au — Au i Ag osadzają się na cynku (cementacja)",
      "Mieszaj przez 2-4h — złoto osadza się na cynku jako szary/brązowy osad",
      "Odsącz osad (Au + Ag + resztki Zn), przemyj wodą",
      "Usunięcie cynku: przenieś osad do naczynia, dodaj rozcieńczony HCl 35% — Zn dissolwuje się, wydziela H2 (brak iskier!); Au i Ag pozostają",
      "Odsącz złoty/srebrny proszek, przemyj 3× wodą destylowaną, wysusz",
      "Przetop proszek w tyglu grafitowym z boraksem — gotowy stop Au/Ag",
    ],
  },
];

router.get("/chemicals/processes", (_req, res) => {
  res.json(chemicalProcesses);
});

export default router;
