import { Router, type IRouter } from "express";

const router: IRouter = Router();

const chemicalProcesses = [
  {
    id: "aqua_regia",
    name: "Woda Królewska (HCl + HNO3)",
    nameEn: "Aqua Regia",
    description:
      "Klasyczna metoda odzysku złota i platynowców. WAŻNE: Przed wodą królewską wsad należy najpierw przetrawić w rozcieńczonym HNO3 (25%), aby usunąć miedź, nikiel i inne metale nieszlachetne — dopiero oczyszczony osad poddaje się wodzie królewskiej. Mieszanina HCl:HNO3 (3:1 obj.) rozpuszcza Au, Pt, Pd. Srebro wytrąca się jako AgCl już w trakcie trawienia.",
    targetMetals: ["Au", "Pt", "Pd"],
    reagents: [
      {
        name: "Kwas azotowy rozcieńczony — pre-trawienie (HNO3 25%)",
        formula: "HNO3",
        concentration: 25,
        amountPerKg: 2.0,
        pricePerLiter: 22.0,
      },
      {
        name: "Kwas solny (HCl)",
        formula: "HCl",
        concentration: 35,
        amountPerKg: 3.0,
        pricePerLiter: 18.0,
      },
      {
        name: "Kwas azotowy stężony (HNO3 65%)",
        formula: "HNO3",
        concentration: 65,
        amountPerKg: 1.0,
        pricePerLiter: 28.0,
      },
      {
        name: "Mocznik (rozkład nadmiaru HNO3)",
        formula: "CO(NH2)2",
        concentration: 99,
        amountPerKg: 0.15,
        pricePerLiter: 4.0,
      },
      {
        name: "Wodorosiarczyn sodu — reduktor SMB (wytrącanie Au)",
        formula: "NaHSO3",
        concentration: 40,
        amountPerKg: 0.3,
        pricePerLiter: 12.0,
      },
      {
        name: "Boraks (topnik do wytopu)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.05,
        pricePerLiter: 10.0,
      },
    ],
    temperatureMin: 50,
    temperatureMax: 90,
    temperatureOptimal: 70,
    timePerKgMin: 6,
    timePerKgMax: 18,
    yieldPercent: { Au: 95, Ag: 20, Pt: 85, Pd: 80 },
    electricityKwhPerKg: 0.6,
    safetyNotes:
      "UWAGA: Wydziela trujące opary NOx i HCl. Praca WYŁĄCZNIE pod sprawnym wyciągiem z aktywnym węglem. Wyposażenie: maska z filtrem ABEK P3, rękawice kwasoodporne (nitril/neopren), fartuch kwasoodporny, gogle ochronne. Nigdy nie wlewaj wody do stężonego kwasu!",
    steps: [
      "KROK 0 — BHP: sprawdź wyciąg, załóż maskę ABEK P3, rękawice i gogle",
      "KROK 1 (pre-trawienie HNO3): wsad rozdrobniony zalej rozcieńczonym HNO3 25% (2 L/kg), podgrzej do 40°C przez 2-3h — usuwa Cu, Ni, Pb, Fe, Sn",
      "KROK 2: Odsącz i przemyj osad (Au, Pt, Pd, AgCl, ceramika) wodą destylowaną — filtrat z HNO3 zachowaj do odzysku Ag i Cu",
      "KROK 3 (woda królewska): przygotuj mieszaninę HCl 35% + HNO3 65% w proporcji 3:1 (obj.) w naczyniu PTFE lub szklano-kwasoodpornym",
      "KROK 4: Powoli wsypuj osad do wody królewskiej, podgrzewaj do 60-70°C mieszając co 30 min — Au, Pt, Pd przechodzą do roztworu",
      "KROK 5: Po rozpuszczeniu (4-8h) odsącz ceramikę i AgCl — AgCl odłóż do dalszego odzysku srebra",
      "KROK 6 (rozkład HNO3): Dodaj mocznik CO(NH2)2 porcjami (ok. 1-2 g na 100 ml) aż ustąpią bąbelki — niszczy nadmiar HNO3, który przeszkadza redukcji",
      "KROK 7 (wytrącanie Au): Powoli dodawaj SMB (NaHSO3) do zimnego roztworu — złoto wytrąca się jako brązowy proszek",
      "KROK 8: Odsącz złoty proszek, przemyj 3× wodą destylowaną, przemyj acetonem, wysusz",
      "KROK 9 (wytop): Umieść proszek w tyglu grafitowym, dodaj szczyptę boraksu jako topnik, przetop palnikiem lub piecem (>1064°C)",
      "KROK 10: Platynę i pallad wytrąć z filtratu — Pt przez NH4Cl (wytrąca (NH4)2PtCl6), Pd przez DMAG lub cementację Cu",
    ],
  },
  {
    id: "hno3_dilute",
    name: "Kwas azotowy rozcieńczony (HNO3 25-30%)",
    nameEn: "Dilute Nitric Acid",
    description:
      "Selektywna metoda odzysku srebra i metali pospolitych (Cu, Ni, Pb). Złoto nie reaguje z rozcieńczonym HNO3 i pozostaje w osadzie jako cenny produkt do dalszej obróbki wodą królewską.",
    targetMetals: ["Ag"],
    reagents: [
      {
        name: "Kwas azotowy rozcieńczony (HNO3 25%)",
        formula: "HNO3",
        concentration: 25,
        amountPerKg: 2.5,
        pricePerLiter: 22.0,
      },
      {
        name: "Chlorek sodu (wytrącanie AgCl)",
        formula: "NaCl",
        concentration: 100,
        amountPerKg: 0.1,
        pricePerLiter: 3.0,
      },
      {
        name: "Cynk metaliczny — redukcja AgCl→Ag",
        formula: "Zn",
        concentration: 99,
        amountPerKg: 0.05,
        pricePerLiter: 65.0,
      },
      {
        name: "Kwas solny HCl — rozpuszczenie cynku z osadu",
        formula: "HCl",
        concentration: 35,
        amountPerKg: 0.2,
        pricePerLiter: 18.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 60,
    temperatureOptimal: 40,
    timePerKgMin: 2,
    timePerKgMax: 6,
    yieldPercent: { Au: 0, Ag: 85, Pt: 5, Pd: 10 },
    electricityKwhPerKg: 0.2,
    safetyNotes:
      "Wydziela opary NO2/NO (brunatne/bezbarwne). Praca pod wyciągiem. Rękawice kwasoodporne obowiązkowe. Uwaga przy etapie HCl — wydziela gaz H2 przy kontakcie z cynkiem.",
    steps: [
      "KROK 0 — BHP: wyciąg, rękawice kwasoodporne, gogle ochronne",
      "KROK 1: Przygotuj HNO3 25% w naczyniu kwasoodpornym",
      "KROK 2: Dodaj wsad elektroniczny porcjami — obserwuj intensywność reakcji (opary NO2)",
      "KROK 3: Mieszaj i podgrzewaj do 40°C przez 2-4h — Cu, Ag, Ni, Pb przechodzą do roztworu",
      "KROK 4: Odsącz osad (Au, Pt, ceramika) — to cenny wsad do procesu wody królewskiej",
      "KROK 5 (wytrącanie Ag): Do filtratu dodaj NaCl — wytrąca się AgCl (biały osad)",
      "KROK 6: Odsącz AgCl, przemyj 3× wodą destylowaną, osusz",
      "KROK 7 (redukcja AgCl→Ag): Umieść AgCl w naczyniu, dodaj granulki cynku (Zn) i przykryj wodą — Zn wypiera Ag z AgCl",
      "KROK 8: Poczekaj 30-60 min (reakcja zwalnia) — odsącz szary proszek Ag + resztki Zn",
      "KROK 9: Dodaj rozcieńczony HCl — dissolwuje Zn, Ag pozostaje; odsącz, przemyj, wysusz proszek Ag",
      "KROK 10: Przetop proszek Ag w tyglu — gotowe metaliczne srebro",
    ],
  },
  {
    id: "hno3_concentrated",
    name: "Kwas azotowy stężony (HNO3 65%)",
    nameEn: "Concentrated Nitric Acid",
    description:
      "Agresywna metoda do wsadów bogatych w miedź i srebro. Stężony HNO3 szybko rozpuszcza metale nieszlachetne, Ag i Pd, pozostawiając Au i Pt w osadzie. Wymaga NaCl do wytrącenia AgCl i cynku do redukcji srebra metalicznego.",
    targetMetals: ["Ag", "Pd"],
    reagents: [
      {
        name: "Kwas azotowy stężony (HNO3 65%)",
        formula: "HNO3",
        concentration: 65,
        amountPerKg: 2.0,
        pricePerLiter: 28.0,
      },
      {
        name: "Chlorek sodu (wytrącanie AgCl)",
        formula: "NaCl",
        concentration: 100,
        amountPerKg: 0.1,
        pricePerLiter: 3.0,
      },
      {
        name: "Cynk metaliczny — redukcja AgCl→Ag",
        formula: "Zn",
        concentration: 99,
        amountPerKg: 0.05,
        pricePerLiter: 65.0,
      },
      {
        name: "Kwas solny HCl — rozpuszczenie cynku z osadu",
        formula: "HCl",
        concentration: 35,
        amountPerKg: 0.2,
        pricePerLiter: 18.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 50,
    temperatureOptimal: 35,
    timePerKgMin: 1,
    timePerKgMax: 4,
    yieldPercent: { Au: 0, Ag: 90, Pt: 0, Pd: 70 },
    electricityKwhPerKg: 0.15,
    safetyNotes:
      "BARDZO NIEBEZPIECZNY. Intensywne opary NOx (brunatny dym). Wymagany sprawny wyciąg z aktywnym węglem. Maska ABEK P3, rękawice kwasoodporne, gogle. Reakcja gwałtowna — dodawaj wsad bardzo powoli i małymi porcjami!",
    steps: [
      "KROK 0 — BHP: wyciąg aktywny, maska ABEK P3, rękawice kwasoodporne, gogle",
      "KROK 1: Wlej stężony HNO3 65% do naczynia kwasoodpornego (PTFE lub szkło borokrzemowe)",
      "KROK 2: Wsad dodawaj BARDZO powoli, porcjami — reakcja jest gwałtowna, brunatne opary NOx",
      "KROK 3: Utrzymuj temperaturę 30-40°C (reakcja egzotermiczna — chłodź w razie potrzeby)",
      "KROK 4: Kontynuuj do zaniku intensywnych oparów (1-3h na kg wsadu)",
      "KROK 5: Odsącz osad (Au, Pt, ceramika) — zachowaj do dalszej obróbki (woda królewska)",
      "KROK 6 (wytrącanie Ag): Do filtratu dodaj NaCl — wytrąca się AgCl (biały osad)",
      "KROK 7: Odsącz AgCl, przemyj 3× wodą destylowaną, osusz",
      "KROK 8 (redukcja AgCl→Ag): Dodaj granulki cynku (Zn) do zawiesiny AgCl z wodą — Zn wypiera Ag",
      "KROK 9: Po 30-60 min odsącz szary proszek Ag+Zn; dodaj HCl — dissolwuje Zn, Ag pozostaje",
      "KROK 10: Odsącz i przemyj proszek Ag, przetop w tyglu — gotowe metaliczne srebro",
    ],
  },
  {
    id: "hcl_h2o2",
    name: "HCl + H2O2 (etching kwasowy)",
    nameEn: "HCl + H2O2 Acid Etching",
    description:
      "Alternatywna metoda dla wody królewskiej. Kwas solny z nadtlenkiem wodoru tworzy chlor in-situ, który rozpuszcza złoto. Bezpieczniejsza alternatywa — bez oparów NOx. Na koniec złoty proszek przetapiany z boraksem.",
    targetMetals: ["Au", "Pd"],
    reagents: [
      {
        name: "Kwas solny (HCl)",
        formula: "HCl",
        concentration: 35,
        amountPerKg: 3.0,
        pricePerLiter: 18.0,
      },
      {
        name: "Nadtlenek wodoru (H2O2)",
        formula: "H2O2",
        concentration: 30,
        amountPerKg: 1.5,
        pricePerLiter: 20.0,
      },
      {
        name: "Wodorosiarczyn sodu — reduktor SMB (wytrącanie Au)",
        formula: "NaHSO3",
        concentration: 40,
        amountPerKg: 0.3,
        pricePerLiter: 12.0,
      },
      {
        name: "Boraks (topnik do wytopu Au)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.05,
        pricePerLiter: 10.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 60,
    temperatureOptimal: 45,
    timePerKgMin: 6,
    timePerKgMax: 24,
    yieldPercent: { Au: 90, Ag: 15, Pt: 60, Pd: 75 },
    electricityKwhPerKg: 0.3,
    safetyNotes:
      "Brak oparów NOx, ale wydziela chlor gazowy (żółtozielony). Praca pod wyciągiem. Rękawice kwasoodporne, gogle. H2O2 dodawaj bardzo ostrożnie — reakcja egzotermiczna; nigdy nie dodawaj dużej porcji naraz.",
    steps: [
      "KROK 0 — BHP: wyciąg, rękawice kwasoodporne, gogle",
      "KROK 1: Wlej HCl 35% do naczynia kwasoodpornego (PTFE lub szkło)",
      "KROK 2: Dodaj wsad elektroniczny (rozdrobniony)",
      "KROK 3: Bardzo powoli, porcjami po 10-20 ml, dodawaj H2O2 30% — pojawi się chlor, reakcja jest egzotermiczna",
      "KROK 4: Mieszaj regularnie, utrzymuj temp. 40-50°C; dodawaj H2O2, gdy reakcja zwalnia",
      "KROK 5: Po 12-24h filtruj — ceramika i nierozpuszczony osad zostają na filtrze",
      "KROK 6 (wytrącanie Au): Ochłodź roztwór; powoli dodawaj SMB (NaHSO3) — brązowy proszek Au wytrąca się",
      "KROK 7: Odsącz złoto, przemyj 3× wodą destylowaną, przemyj acetonem, wysusz",
      "KROK 8: Wytop proszek Au w tyglu grafitowym z szczyptą boraksu jako topnikiem (>1064°C)",
    ],
  },
  {
    id: "nitrate_boat",
    name: "Łódź azotanowa (NaNO3 + H2SO4)",
    nameEn: "Nitrate Boat (NaNO3 + H2SO4)",
    description:
      "Stara metoda rafinacyjna stosowana przez jubilerów. Mieszanina azotanu sodu i kwasu siarkowego tworzy kwas azotowy in-situ. Skuteczna do oczyszczania stopów złota. Wymaga NaCl do wytrącenia Ag i SMB do wytrącenia Au z roztworu.",
    targetMetals: ["Au", "Ag"],
    reagents: [
      {
        name: "Azotan sodu (NaNO3)",
        formula: "NaNO3",
        concentration: 99,
        amountPerKg: 0.5,
        pricePerLiter: 18.0,
      },
      {
        name: "Kwas siarkowy (H2SO4)",
        formula: "H2SO4",
        concentration: 98,
        amountPerKg: 1.5,
        pricePerLiter: 28.0,
      },
      {
        name: "Chlorek sodu (wytrącanie AgCl)",
        formula: "NaCl",
        concentration: 100,
        amountPerKg: 0.1,
        pricePerLiter: 3.0,
      },
      {
        name: "Wodorosiarczyn sodu — SMB (wytrącanie Au)",
        formula: "NaHSO3",
        concentration: 40,
        amountPerKg: 0.3,
        pricePerLiter: 12.0,
      },
    ],
    temperatureMin: 60,
    temperatureMax: 120,
    temperatureOptimal: 90,
    timePerKgMin: 3,
    timePerKgMax: 8,
    yieldPercent: { Au: 85, Ag: 90, Pt: 30, Pd: 40 },
    electricityKwhPerKg: 0.8,
    safetyNotes:
      "BARDZO WYSOKA TEMPERATURA + opary NOx. H2SO4 98% jest silnie egzotermiczny z wodą — nigdy nie dodawaj wody do stężonego H2SO4! Maska ABEK P3, rękawice kwasoodporne odporne na wysokie temperatury (neopren), fartuch, gogle. Wyciąg obowiązkowy.",
    steps: [
      "KROK 0 — BHP: wyciąg z aktywnym węglem, maska ABEK P3, rękawice termooodporne i kwasoodporne, gogle",
      "KROK 1: Wlej H2SO4 98% do naczynia żaroodpornego i kwasoodpornego (kwarc lub niobian)",
      "KROK 2: Stopniowo dodawaj NaNO3 do kwasu — NIE odwrotnie! Mieszaj do rozpuszczenia",
      "KROK 3: Podgrzewaj do 80-100°C przy ciągłym mieszaniu — tworzy się HNO3 in-situ",
      "KROK 4: Dodaj rozdrobniony wsad (złom elektroniczny) porcjami",
      "KROK 5: Utrzymuj temperaturę 80-100°C przez 3-6h — metale przechodzą do roztworu",
      "KROK 6: Ostudź do temperatury pokojowej; ostrożnie rozcieńcz wodą (SILNIE EGZOTERMICZNE — dodawaj wodę do kwasu, nie odwrotnie!)",
      "KROK 7 (wytrącanie Ag): Do filtratu dodaj NaCl — biały osad AgCl; odsącz, przemyj, osusz",
      "KROK 8 (wytrącanie Au): Do filtratu bez AgCl dodaj SMB (NaHSO3) — brązowy proszek Au wytrąca się",
      "KROK 9: Odsącz złoto, przemyj, wysusz i przetop w tyglu grafitowym",
    ],
  },
  {
    id: "electrolysis",
    name: "Elektroliza (rafinacja elektrolityczna)",
    nameEn: "Electrolytic Refining",
    description:
      "Selektywna metoda rafinacji złota. Złoto z anody przechodzi do katody jako czysty metal 999+. Wymaga wstępnego stopienia wsadu w anodę (z boraksem jako topnikiem). Elektrolit: HNO3 10% + Au(NO3)3.",
    targetMetals: ["Au", "Ag"],
    reagents: [
      {
        name: "Kwas azotowy (elektrolit bazowy)",
        formula: "HNO3",
        concentration: 10,
        amountPerKg: 2.0,
        pricePerLiter: 18.0,
      },
      {
        name: "Azotan złota (Au(NO3)3, uzupełniacz elektrolitu)",
        formula: "Au(NO3)3",
        concentration: 5,
        amountPerKg: 0.1,
        pricePerLiter: 1800.0,
      },
      {
        name: "Boraks (topnik do wytopu anody)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.1,
        pricePerLiter: 10.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 50,
    temperatureOptimal: 30,
    timePerKgMin: 8,
    timePerKgMax: 48,
    yieldPercent: { Au: 99, Ag: 95, Pt: 60, Pd: 50 },
    electricityKwhPerKg: 2.5,
    safetyNotes:
      "Elektroliza sama w sobie jest stosunkowo bezpieczna. Jednak elektrolit (HNO3 10%) jest żrący — rękawice nitrylowe i gogle. Etap wytopu anody wymaga palnika (>1064°C) — środki ochrony p.poż.",
    steps: [
      "KROK 0 — BHP: rękawice nitrylowe, gogle; przy wytocie anody — osłona termiczna",
      "KROK 1 (wytop anody): Przetop wsad w tyglu grafitowym z boraksem jako topnikiem — uformuj anodę (blok/płytka)",
      "KROK 2: Przygotuj elektrolit: HNO3 10% + Au(NO3)3 w wannie elektrolitycznej, podgrzej do 25-30°C",
      "KROK 3: Zamontuj anodę (wsad) i katodę (folia tytanowa lub czyste Au)",
      "KROK 4: Ustaw napięcie 0.5-1.5V, gęstość prądu 50-200 A/m²",
      "KROK 5: Elektrolizuj 12-48h — złoto osadza się na katodzie jako czysty metal 999+",
      "KROK 6: Regularnie zbieraj szlam anodowy (Pt, Pd, Ag, inne metale szlachetne) do dalszej obróbki",
      "KROK 7: Wyjmij katodę, oczyść z elektrolitu, przemyj wodą destylowaną, przetop",
      "KROK 8: Wynik — złoto 999+ czystości; szlam anodowy przetworzyć wodą królewską lub Wöhlwillem",
    ],
  },
  {
    id: "wohlwill_process",
    name: "Proces Wöhlwilla (rafinacja złota 999.9)",
    nameEn: "Wohlwill Process",
    description:
      "Przemysłowy proces elektrolityczny dla złota najwyższej czystości (999.9). Elektrolit na bazie chlorku złota (AuCl3) w HCl. Standard dla mennic i rafinerii. Wymaga wstępnego wytopu anod z boraksem jako topnikiem.",
    targetMetals: ["Au"],
    reagents: [
      {
        name: "Kwas solny (elektrolit bazowy HCl 20%)",
        formula: "HCl",
        concentration: 20,
        amountPerKg: 3.0,
        pricePerLiter: 12.0,
      },
      {
        name: "Chlorek złota (AuCl3, uzupełniacz elektrolitu)",
        formula: "AuCl3",
        concentration: 10,
        amountPerKg: 0.2,
        pricePerLiter: 3200.0,
      },
      {
        name: "Boraks (topnik do wytopu anod)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.05,
        pricePerLiter: 10.0,
      },
    ],
    temperatureMin: 60,
    temperatureMax: 75,
    temperatureOptimal: 70,
    timePerKgMin: 24,
    timePerKgMax: 72,
    yieldPercent: { Au: 99.5, Ag: 0, Pt: 30, Pd: 20 },
    electricityKwhPerKg: 3.0,
    safetyNotes:
      "Wysoka temperatura elektrolitu (65-70°C). Opary HCl — wyciąg obowiązkowy. Rękawice kwasoodporne, gogle. Etap wytopu anod wymaga palnika (>1064°C) — osłona termiczna. Koszt AuCl3 bardzo wysoki — opłacalny tylko dla wsadów z >90% Au.",
    steps: [
      "KROK 0 — BHP: wyciąg aktywny (opary HCl), rękawice kwasoodporne, gogle; przy wytocie — osłona termiczna",
      "KROK 1 (wytop anod): Przetop wsad (wymagany min. 90% Au) w tyglu grafitowym z boraksem jako topnikiem — uformuj anody (płytki ~5-10mm)",
      "KROK 2: Przygotuj elektrolit: HCl 20% + AuCl3 10% w wannie kwasoodpornej, podgrzej do 65-70°C",
      "KROK 3: Zamontuj anody i katody (folia tytanowa lub czyste Au)",
      "KROK 4: Ustaw parametry: U=1.0-1.2V, gęstość prądu 500-1000 A/m², T=65-70°C",
      "KROK 5: Elektrolizuj 24-72h — złoto 999.9 osadza się na katodach jako kryształy",
      "KROK 6: Pobierz katody, oczyść z elektrolitu wodą destylowaną, osusz",
      "KROK 7: Przetop katody w tyglu grafitowym — gotowe złoto 999.9",
      "KROK 8: Szlam anodowy (Pt, Pd, Ag) przetworzyć oddzielnie (kwas azotowy lub woda królewska)",
    ],
  },
  {
    id: "miller_process",
    name: "Proces Millera (chloracja pirometalurgiczna)",
    nameEn: "Miller Process (Chlorination)",
    category: "pyrometallurgical",
    description:
      "Przemysłowa metoda oczyszczania złota przez nadmuch chloru do stopionego metalu w piecu indukcyjnym. Zanieczyszczenia (Ag, Cu, Pb, Zn) reagują z Cl2, tworząc chlorki które pływają na powierzchni. Złoto pozostaje czyste (99.0-99.5%). WYMAGA instalacji neutralizacji Cl2 (NaOH).",
    targetMetals: ["Au"],
    reagents: [
      {
        name: "Chlor gazowy (Cl2)",
        formula: "Cl2",
        concentration: 99,
        amountPerKg: 0.5,
        pricePerLiter: 38.0,
      },
      {
        name: "Boraks (topnik)",
        formula: "Na2B4O7",
        concentration: 99,
        amountPerKg: 0.3,
        pricePerLiter: 10.0,
      },
      {
        name: "Wodorotlenek sodu NaOH 30% (neutralizacja Cl2 w off-gazie)",
        formula: "NaOH",
        concentration: 30,
        amountPerKg: 1.0,
        pricePerLiter: 8.0,
      },
    ],
    temperatureMin: 1064,
    temperatureMax: 1200,
    temperatureOptimal: 1100,
    timePerKgMin: 0.5,
    timePerKgMax: 2,
    yieldPercent: { Au: 98, Ag: 0, Pt: 20, Pd: 10 },
    electricityKwhPerKg: 5.0,
    safetyNotes:
      "EKSTREMALNIE NIEBEZPIECZNY — chlor gazowy jest silnie toksyczny (LC50=430 mg/m³). WYMAGANY szczelny system z pełną instalacją scrubberową NaOH. Tylko dla profesjonalnych rafinerii z certyfikowanym wyposażeniem, systemem wentylacji i szkolonym personelem. NIE dla amatorów.",
    steps: [
      "KROK 0 — BHP: certyfikowany scrubber Cl2 z NaOH, maska z filtrem B2P3 lub aparat powietrzny, kombinezon kwasoodporny, wyciąg przemysłowy — MINIMUM",
      "KROK 1: Uruchom piec indukcyjny, nagrzej tygiel grafitowy do 1100°C",
      "KROK 2: Dodaj wsad (stop złota) i boraks jako topnik — poczekaj do pełnego stopienia",
      "KROK 3: Podłącz instalację Cl2 (rura kwarc/glinka) — sprawdź szczelność systemu scrubberowego",
      "KROK 4: Wdmuchuj Cl2 powoli do stopionego metalu — obserwuj kolor płomienia (żółty = AgCl, biały = PbCl2/ZnCl2)",
      "KROK 5: Off-gaz Cl2 przechodzi przez scrubber NaOH — sprawdzaj pochłanianie (papierek lakmusowy)",
      "KROK 6: Kontynuuj do zaniku barwnych płomieni i klarowania stopionego złota (0.5-2h)",
      "KROK 7: Zatrzymaj dopływ Cl2, spuść złocisty metal do form — wynik: Au 99.0-99.5%",
      "KROK 8: Chlorki z powierzchni (szlam) przetworzyć do odzysku Ag — zawierają AgCl",
    ],
  },
  {
    id: "cementation_zinc",
    name: "Cementacja cynkiem (wytrącanie Au)",
    nameEn: "Zinc Cementation",
    description:
      "Klasyczna metoda wytrącania złota z roztworu (np. cyjanku lub chlorku) przez dodanie cynku. Cynk wypiera złoto z roztworu — cementacja. Po cementacji cynk rozpuszcza się w HCl, a złoto pozostaje jako proszek.",
    targetMetals: ["Au", "Ag"],
    reagents: [
      {
        name: "Cynk metaliczny (granulki Zn)",
        formula: "Zn",
        concentration: 99,
        amountPerKg: 0.4,
        pricePerLiter: 65.0,
      },
      {
        name: "Ług cyjanku sodu (NaCN, opcjonalny — do ługowania)",
        formula: "NaCN",
        concentration: 5,
        amountPerKg: 1.0,
        pricePerLiter: 40.0,
      },
      {
        name: "Kwas solny HCl (rozpuszczenie cynku z osadu Au+Zn)",
        formula: "HCl",
        concentration: 35,
        amountPerKg: 0.5,
        pricePerLiter: 18.0,
      },
    ],
    temperatureMin: 20,
    temperatureMax: 60,
    temperatureOptimal: 40,
    timePerKgMin: 2,
    timePerKgMax: 8,
    yieldPercent: { Au: 80, Ag: 75, Pt: 20, Pd: 30 },
    electricityKwhPerKg: 0.1,
    safetyNotes:
      "KRYTYCZNE przy NaCN — cyjanki są silnie toksyczne (śmiertelne)! Pracuj ZAWSZE przy pH > 10 (zasadowe). Nigdy nie mieszaj NaCN z kwasem (wydzielanie HCN!). Etap HCl do cynku jest bezpieczny, ale wydziela H2 — iskry niedopuszczalne.",
    steps: [
      "KROK 0 — BHP: przy NaCN — maska z filtrem B2P3, rękawice nitrylowe, wyciąg; antidotum (Na2S2O3) pod ręką",
      "KROK 1: Przygotuj roztwór zawierający Au (np. po ługowaniu cyjankowym lub chlorkowym)",
      "KROK 2 (KRYTYCZNE przy NaCN): Doprowadź pH do 10-12 (dodaj Ca(OH)2 lub NaOH) — nigdy przy niższym pH!",
      "KROK 3: Dodaj granulki cynku (Zn) do roztworu — Au i Ag osadzają się na cynku (cementacja)",
      "KROK 4: Mieszaj przez 2-4h — złoto osadza się na cynku jako szary/brązowy osad",
      "KROK 5: Odsącz osad (Au + Ag + resztki Zn), przemyj wodą",
      "KROK 6 (usunięcie cynku): Przenieś osad do nowego naczynia, dodaj rozcieńczony HCl 35% — Zn dissolwuje się, wydziela H2 (brak iskier!); Au i Ag pozostają",
      "KROK 7: Odsącz złoty/srebrny proszek, przemyj 3× wodą destylowaną, wysusz",
      "KROK 8: Przetop proszek w tyglu grafitowym z boraksem — gotowy stop Au/Ag",
    ],
  },
];

router.get("/chemicals/processes", (_req, res) => {
  res.json(chemicalProcesses);
});

export default router;
