import { Router, type IRouter } from "express";

const router: IRouter = Router();

export const electronicMaterials = [
  // ─── PŁYTY GŁÓWNE (DESKTOP) ───────────────────────────────────────────────
  {
    id: "mb_stare",
    name: "Płyty główne (stare)",
    nameEn: "Motherboards (old)",
    category: "plyty_glowne",
    unit: "kg",
    weightPerPiece: 0.75,
    metalContentPerKg: {
      Au: { min: 0.18, max: 0.80, typical: 0.40 },
      Ag: { min: 0.30, max: 1.80, typical: 0.90 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.02, max: 0.10, typical: 0.05 },
    },
    notes: "Stare płyty główne desktop ISA/AT/ATX (przed ~2004) — bez aluminium, stali, baterii, wiatraków. Au z gniazd, złączek i IC bond wires. Ag niska – lutowie ołowiowe bez Ag. Pd z MLCC starszej generacji.",
  },
  {
    id: "mb_stare_socket",
    name: "Płyty główne (stare, socket 370/423/462)",
    nameEn: "Motherboards (old socket 370/423/462)",
    category: "plyty_glowne",
    unit: "kg",
    weightPerPiece: 0.70,
    metalContentPerKg: {
      Au: { min: 0.12, max: 0.55, typical: 0.32 },
      Ag: { min: 0.25, max: 1.50, typical: 0.75 },
      Pt: { min: 0.0, max: 0.01, typical: 0.004 },
      Pd: { min: 0.015, max: 0.08, typical: 0.04 },
    },
    notes: "Płyty główne socket 370 (PIII), 423/462 (P4/Athlon XP, era 2000-2004) — bez aluminium, baterii, wiatraków. Lutowie Pb-Sn → niskie Ag. Au z gniazd PCI/AGP/RAM i blaszek kontaktowych.",
  },
  {
    id: "mb_nowe_0bga",
    name: "Płyty główne (nowe 0BGA)",
    nameEn: "Motherboards (new 0BGA)",
    category: "plyty_glowne",
    unit: "kg",
    weightPerPiece: 0.35,
    metalContentPerKg: {
      Au: { min: 0.03, max: 0.12, typical: 0.06 },
      Ag: { min: 0.4, max: 1.8, typical: 0.9 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.005, max: 0.04, typical: 0.018 },
    },
    notes: "Nowoczesne płyty główne bez układów BGA (bez aluminium, stali, baterii, wiatraków). metalContentPerKg liczone dla płyty jako całości.",
  },
  {
    id: "mb_nowe_1bga",
    name: "Płyty główne (nowe 1BGA)",
    nameEn: "Motherboards (new 1BGA)",
    category: "plyty_glowne",
    unit: "kg",
    weightPerPiece: 0.50,
    metalContentPerKg: {
      Au: { min: 0.06, max: 0.20, typical: 0.11 },
      Ag: { min: 0.6, max: 2.5, typical: 1.3 },
      Pt: { min: 0.0, max: 0.008, typical: 0.003 },
      Pd: { min: 0.008, max: 0.06, typical: 0.028 },
    },
    notes: "Nowoczesne płyty główne z jednym dużym układem BGA (np. chipset) — bez aluminium, stali, baterii, wiatraków.",
  },
  {
    id: "mb_nowe_2bga",
    name: "Płyty główne (nowe 2BGA)",
    nameEn: "Motherboards (new 2BGA)",
    category: "plyty_glowne",
    unit: "kg",
    weightPerPiece: 0.60,
    metalContentPerKg: {
      Au: { min: 0.09, max: 0.30, typical: 0.16 },
      Ag: { min: 0.8, max: 3.0, typical: 1.7 },
      Pt: { min: 0.0, max: 0.01, typical: 0.004 },
      Pd: { min: 0.01, max: 0.08, typical: 0.04 },
    },
    notes: "Nowoczesne płyty główne z dwoma dużymi układami BGA — bez aluminium, stali, baterii, wiatraków.",
  },
  {
    id: "mb_serwerowe",
    name: "Płyty główne serwerowe (dual)",
    nameEn: "Server motherboards (dual CPU)",
    category: "plyty_glowne",
    unit: "kg",
    weightPerPiece: 1.50,
    metalContentPerKg: {
      Au: { min: 0.30, max: 1.50, typical: 0.65 },
      Ag: { min: 0.80, max: 3.00, typical: 1.60 },
      Pt: { min: 0.0, max: 0.02, typical: 0.008 },
      Pd: { min: 0.03, max: 0.18, typical: 0.09 },
    },
    notes: "Płyty serwerowe dual CPU (Xeon, EPYC) — bez aluminium, stali, baterii, wiatraków. Wyższe Au niż desktop: więcej gniazd, złączek DIMM i ECC connectorów. Zawiera Ag z lutowia RoHS (SnAg) jeśli model po 2007.",
  },

  // ─── PŁYTY GŁÓWNE LAPTOPOWE ───────────────────────────────────────────────
  {
    id: "mb_laptop_stare",
    name: "Płyty główne laptopowe (stare)",
    nameEn: "Laptop motherboards (old)",
    category: "plyty_glowne",
    unit: "kg",
    weightPerPiece: 0.20,
    metalContentPerKg: {
      Au: { min: 0.12, max: 0.45, typical: 0.26 },
      Ag: { min: 0.20, max: 1.50, typical: 0.80 },
      Pt: { min: 0.0, max: 0.01, typical: 0.004 },
      Pd: { min: 0.015, max: 0.10, typical: 0.055 },
    },
    notes: "Stare płyty laptopowe (~200g/szt, bez aluminium, blachy, folii). Au z gniazd, złączek, bond wires. Ag NISKA — stare laptopy (pre-2006) używały lutowia Pb-Sn bez srebra; Ag pochodzi głównie ze starszych MLCC (PME) z elektrodami Pd-Ag. Badania: Ag 0.3-1.5 g/kg dla starszych płyt laptopowych.",
  },
  {
    id: "mb_laptop_nowe_0bga",
    name: "Płyty główne laptopowe (nowe 0BGA)",
    nameEn: "Laptop motherboards (new 0BGA)",
    category: "plyty_glowne",
    unit: "kg",
    weightPerPiece: 0.15,
    metalContentPerKg: {
      Au: { min: 0.04, max: 0.15, typical: 0.08 },
      Ag: { min: 0.4, max: 2.0, typical: 1.0 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.01, max: 0.06, typical: 0.03 },
    },
    notes: "Nowoczesne płyty laptopowe bez układów BGA — bez aluminium, blachy, folii.",
  },

  // ─── PŁYTY PCB OGÓLNE ─────────────────────────────────────────────────────
  {
    id: "pcb_klasa_b",
    name: "Płyty klasy B (zielone)",
    nameEn: "Class B PCB (green)",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.15,
    requiresCleaning: true,
    cleanedMultiplier: { Au: 1.18, Ag: 1.18, Pt: 1.18, Pd: 1.18 },
    metalContentPerKg: {
      Au: { min: 0.04, max: 0.20, typical: 0.10 },
      Ag: { min: 0.5, max: 2.5, typical: 1.2 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.005, max: 0.05, typical: 0.02 },
    },
    notes: "Zielone płytki PCB klasy B (B1-B5) — bez blachy i aluminium. metalContentPerKg uwzględnia całą płytkę z komponentami.",
  },
  {
    id: "pcb_klasa_c",
    name: "Płyty klasy C (żółte i brązowe)",
    nameEn: "Class C PCB (yellow/brown)",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.10,
    requiresCleaning: true,
    cleanedMultiplier: { Au: 1.15, Ag: 1.15, Pt: 1.15, Pd: 1.15 },
    metalContentPerKg: {
      Au: { min: 0.01, max: 0.08, typical: 0.04 },
      Ag: { min: 0.2, max: 1.2, typical: 0.6 },
      Pt: { min: 0.0, max: 0.002, typical: 0.001 },
      Pd: { min: 0.002, max: 0.02, typical: 0.008 },
    },
    notes: "Żółte i brązowe płytki PCB klasy C — starsza technologia, mniej metali szlachetnych. Bez blachy i aluminium.",
  },
  {
    id: "pcb_telecom",
    name: "Płytka PCB (telekomunikacyjna)",
    nameEn: "Telecom PCB",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.30,
    requiresCleaning: true,
    cleanedMultiplier: { Au: 1.15, Ag: 1.15, Pt: 1.15, Pd: 1.15 },
    metalContentPerKg: {
      Au: { min: 0.10, max: 0.50, typical: 0.25 },
      Ag: { min: 0.50, max: 3.00, typical: 1.50 },
      Pt: { min: 0.0, max: 0.02, typical: 0.008 },
      Pd: { min: 0.008, max: 0.06, typical: 0.025 },
    },
    catalogHint: "green/yellow circuit board from router, switch or modem — FR4 substrate with chips and SMD parts, NO dense arrays of gold pins",
    notes: "Płyty PCB z urządzeń telekomunikacyjnych (routery, switche, modemy ~300g/szt). Badania Holgersson 2018: Au 199 ppm, Ag 1213 ppm, Pd 19.5 ppm. Ag z lutowia SnAg i MLCC. Wyższe Au niż typowe PCB. UWAGA: NIE dla złączy/konektorów backplane z central telefonicznych — te mają osobną kategorię z ~10× wyższym Au.",
  },
  {
    id: "telecom_backplane_connector",
    name: "Złącza backplane z central telefonicznych (DIN/Metral)",
    nameEn: "Telecom exchange backplane connectors (DIN/Metral)",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.80,
    requiresCleaning: true,
    cleanedMultiplier: { Au: 1.25, Ag: 1.15, Pt: 1.15, Pd: 1.20 },
    catalogHint: "DENSE ARRAY of hundreds of shiny gold-colored pins in a block/housing — connector assembly from telephone exchange, no green PCB substrate, looks like a golden comb or grid of pins",
    metalContentPerKg: {
      Au: { min: 1.0, max: 8.0, typical: 3.0 },
      Ag: { min: 0.5, max: 3.0, typical: 1.2 },
      Pt: { min: 0.0, max: 0.02, typical: 0.005 },
      Pd: { min: 0.05, max: 0.40, typical: 0.15 },
    },
    notes: "Złącza DIN 41612 / 2mm Metral / wysokogęstościowe konektory backplane z central Ericsson AXE, Siemens EWSD, Alcatel E10, Nortel DMS — same złącza bez płytki FR4. Setki do tysięcy złoconych pinów (0,5–2,5 µm Au). Dane branżowe e-waste: 2–8 g/kg Au dla frakcji złączy. Nie mylić z płytkami PCB z tych central (osobna kategoria). Masa typowego zestawu złączy z jednego subrack: 0,5–2 kg.",
  },
  {
    id: "telecom_crossbar_contacts",
    name: "Releje / styki krzyżownicy (centrale elektromechaniczne)",
    nameEn: "Crossbar switch relay contacts (electromechanical exchanges)",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.50,
    requiresCleaning: true,
    cleanedMultiplier: { Au: 1.15, Ag: 1.15, Pt: 1.10, Pd: 1.15 },
    catalogHint: "electromechanical relay springs and contact points from old telephone crossbar switch — metallic springs with contact dots, mechanical matrix, no PCB substrate",
    metalContentPerKg: {
      Au: { min: 2.0, max: 10.0, typical: 5.0 },
      Ag: { min: 1.0, max: 8.0, typical: 4.0 },
      Pt: { min: 0.0, max: 0.05, typical: 0.01 },
      Pd: { min: 0.10, max: 1.50, typical: 0.50 },
    },
    notes: "Styki kontaktowe krzyżownicy z central elektromechanicznych (Ericsson ARF/ARM, Siemens EMD, Strowger, Panel switch — epoka 1950–1980). Sprężyny kontaktowe ze stopu Au-Pd-Ag lub pokryte Au/Pd. 100 punktów kontaktowych na jednostkę krzyżownicy. Bardzo wysoki uzysk Au+Pd — najlepsza frakcja telecom e-waste. Dane: 3–10 g/kg Au, do 1,5 g/kg Pd. Separować od blachy stalowej przed procesem.",
  },
  {
    id: "telecom_pcb_linecard",
    name: "Płytki linii abonenckiej / karty modułowe (centrale cyfrowe)",
    nameEn: "Line cards / module boards (digital exchanges)",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.25,
    requiresCleaning: true,
    cleanedMultiplier: { Au: 1.15, Ag: 1.15, Pt: 1.15, Pd: 1.15 },
    catalogHint: "PCB board with chips from telephone exchange cabinet — has edge connector or DIN connector on one end, green/yellow substrate with ICs and components",
    metalContentPerKg: {
      Au: { min: 0.30, max: 1.50, typical: 0.70 },
      Ag: { min: 0.80, max: 4.00, typical: 2.00 },
      Pt: { min: 0.0, max: 0.02, typical: 0.008 },
      Pd: { min: 0.02, max: 0.15, typical: 0.06 },
    },
    notes: "Karty PCB linii abonenckiej, karty procesora, karty sygnalizacji z central cyfrowych (Ericsson AXE10, Siemens EWSD, Alcatel E10 — epoka 1980–2005). Wyższe Au niż typowy telecom PCB: dedykowane piny, złączone złaczami DIN, złocone krawędziowe złącza. Nie zawiera złączy — same płytki. ~250g/szt.",
  },
  {
    id: "pcb_smd",
    name: "Elementy SMD / BGA (preselekcjonowane)",
    nameEn: "SMD Components / BGA (preselected)",
    category: "pcb",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.2, max: 1.0, typical: 0.5 },
      Ag: { min: 2.0, max: 8.0, typical: 4.0 },
      Pt: { min: 0.0, max: 0.05, typical: 0.02 },
      Pd: { min: 0.05, max: 0.3, typical: 0.15 },
    },
    notes: "Preselekcjonowane drobne elementy SMD i kulki BGA — wyceniane wyłącznie w kg.",
  },

  // ─── PŁYTY Z URZĄDZEŃ ─────────────────────────────────────────────────────
  {
    id: "pcb_hdd_stare",
    name: "Płyty z dysków twardych HDD (stare, do ~2005)",
    nameEn: "Old HDD PCBs (pre-2005)",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.050,
    metalContentPerKg: {
      Au: { min: 0.35, max: 0.85, typical: 0.55 },
      Ag: { min: 1.0, max: 3.5, typical: 2.0 },
      Pt: { min: 0.0, max: 0.02, typical: 0.008 },
      Pd: { min: 0.03, max: 0.18, typical: 0.09 },
    },
    notes: "Płytki PCB z dysków sprzed 2005 r. — grubsze złocenia ścieżek, DIP IC, gęste złącza. Dane: ok. 0.35–0.85 g Au/kg wg danych recyklerów.",
  },
  {
    id: "pcb_hdd_nowe",
    name: "Płyty z dysków twardych HDD (nowe, po 2005)",
    nameEn: "Modern HDD PCBs (post-2005)",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.040,
    metalContentPerKg: {
      Au: { min: 0.08, max: 0.32, typical: 0.18 },
      Ag: { min: 0.5, max: 2.0, typical: 1.1 },
      Pt: { min: 0.0, max: 0.01, typical: 0.004 },
      Pd: { min: 0.01, max: 0.08, typical: 0.04 },
    },
    notes: "Płytki PCB z dysków po 2005 r. — SMD, cieńsze złocenia, mniej Pd w kondensatorach. Dane: ok. 0.08–0.32 g Au/kg wg pomiarów recyklerów.",
  },
  {
    id: "pcb_cdrom",
    name: "Płyty z napędów CD-ROM",
    nameEn: "CD-ROM drive PCBs",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.040,
    metalContentPerKg: {
      Au: { min: 0.12, max: 0.35, typical: 0.20 },
      Ag: { min: 0.8, max: 2.5, typical: 1.5 },
      Pt: { min: 0.0, max: 0.008, typical: 0.003 },
      Pd: { min: 0.01, max: 0.06, typical: 0.028 },
    },
    notes: "Płyty elektroniki z napędów CD-ROM/DVD (ok. 35-45g/szt) — bez obudowy.",
  },
  {
    id: "pcb_telefon_stare",
    name: "Płyty z telefonów komórkowych (starych)",
    nameEn: "Old mobile phone PCBs",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.025,
    metalContentPerKg: {
      Au: { min: 0.20, max: 0.80, typical: 0.45 },
      Ag: { min: 1.5, max: 5.0, typical: 3.0 },
      Pt: { min: 0.0, max: 0.01, typical: 0.004 },
      Pd: { min: 0.02, max: 0.15, typical: 0.08 },
    },
    notes: "Płyty ze starych telefonów komórkowych (ok. 20-30g/szt, bez wyświetlaczy). metalContentPerKg uwzględnia cały moduł płyty.",
  },
  {
    id: "pcb_telefon_nowe",
    name: "Płyty z telefonów komórkowych (nowych)",
    nameEn: "New mobile phone PCBs",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.020,
    metalContentPerKg: {
      Au: { min: 0.18, max: 0.80, typical: 0.40 },
      Ag: { min: 0.15, max: 0.80, typical: 0.35 },
      Pt: { min: 0.0, max: 0.008, typical: 0.003 },
      Pd: { min: 0.015, max: 0.10, typical: 0.055 },
    },
    notes: "Płyty logiczne z nowych smartfonów (~15-25g/szt, bez wyświetlaczy). Au: badania JSDEWES i UN-Univ. podają 1071 ppm (1.07 g/kg) dla samego PCB; nasza wartość jest niższa bo materiał zawiera też obudowę, filtry RF, złącza. Ag: głównie z lutowia RoHS (SnAg SAC305 3% Ag) i MLCC. Pd: z BME-MLCC (nowe typy — niskie).",
  },
  {
    id: "pcb_auto",
    name: "Płyty z komputerów samochodowych",
    nameEn: "Automotive ECU PCBs",
    category: "pcb",
    unit: "kg",
    weightPerPiece: 0.20,
    metalContentPerKg: {
      Au: { min: 0.06, max: 0.25, typical: 0.13 },
      Ag: { min: 0.5, max: 2.5, typical: 1.3 },
      Pt: { min: 0.0, max: 0.01, typical: 0.004 },
      Pd: { min: 0.01, max: 0.08, typical: 0.04 },
    },
    notes: "Płyty elektroniczne z komputerów samochodowych i sterowników ECU.",
  },

  // ─── PROCESORY ────────────────────────────────────────────────────────────
  {
    id: "cpu_ceramic_486",
    name: "Procesory ceramiczne (Intel 486)",
    nameEn: "Ceramic CPU (Intel 486)",
    category: "procesor",
    unit: "kg",
    weightPerPiece: 0.040,
    metalContentPerKg: {
      Au: { min: 5.0, max: 14.0, typical: 7.0 },
      Ag: { min: 1.0, max: 4.0, typical: 2.0 },
      Pt: { min: 0.0, max: 0.12, typical: 0.05 },
      Pd: { min: 0.06, max: 0.50, typical: 0.22 },
    },
    notes: "Ceramiczne procesory Intel 286/386/486 (~40g/szt) — złota pokrywa (lid), złocone nóżki (PGA), gold bond wires w IC. GoldRefiningForum assay: 486DX2/DX4 = 6.4-8.0 g/kg; modele wojskowe (CHMOS, MIL-SPEC) do 14 g/kg. Skup (ecocenter.com.pl 2025): 2200-2800 zł/kg. Typowa wartość 7.0 g/kg odpowiada ok. 3700 PLN przychodu/kg z wody królewskiej.",
  },
  {
    id: "cpu_ceramic_2str",
    name: "Procesory ceramiczne złote (2 strony)",
    nameEn: "Ceramic gold CPU (2 sides)",
    category: "procesor",
    unit: "kg",
    weightPerPiece: 0.048,
    metalContentPerKg: {
      Au: { min: 3.5, max: 10.0, typical: 6.0 },
      Ag: { min: 1.5, max: 6.0, typical: 3.0 },
      Pt: { min: 0.0, max: 0.12, typical: 0.05 },
      Pd: { min: 0.05, max: 0.35, typical: 0.18 },
    },
    notes: "Ceramiczne procesory ze złotą powłoką z obu stron (złota czapa + złota spodnia strona, ~48g/szt). GRF assay: Gold Bottom + Gold Top = 6.25 g/kg. Skup: 800-1000 zł/kg. Ag z MLCC i wewnętrznych przewodów bonding.",
  },
  {
    id: "cpu_ceramic_1str",
    name: "Procesory ceramiczne złote (1 strona)",
    nameEn: "Ceramic gold CPU (1 side)",
    category: "procesor",
    unit: "kg",
    weightPerPiece: 0.040,
    metalContentPerKg: {
      Au: { min: 1.8, max: 7.0, typical: 4.0 },
      Ag: { min: 0.6, max: 3.0, typical: 1.6 },
      Pt: { min: 0.0, max: 0.10, typical: 0.04 },
      Pd: { min: 0.02, max: 0.22, typical: 0.10 },
    },
    notes: "Ceramiczne procesory ze złotem tylko na jednej stronie (~40g/szt). GRF assay: Gold Bottom + Black Top = 5.82 g/kg; Black Bottom + Gold Top = 2.71 g/kg → średnia typowych partii ~3.5-4.5 g/kg. Skup: 700-900 zł/kg.",
  },
  {
    id: "cpu_ceramic_nozki",
    name: "Procesory ceramiczne złote nóżki",
    nameEn: "Ceramic CPU gold legs",
    category: "procesor",
    unit: "kg",
    weightPerPiece: 0.048,
    metalContentPerKg: {
      Au: { min: 1.2, max: 4.5, typical: 2.2 },
      Ag: { min: 0.5, max: 2.5, typical: 1.2 },
      Pt: { min: 0.0, max: 0.08, typical: 0.03 },
      Pd: { min: 0.015, max: 0.15, typical: 0.07 },
    },
    notes: "Ceramiczne procesory tylko ze złotymi nóżkami PGA, bez złotej czapy na ceramice (~48g/szt). GRF assay: Simple Ceramic no gold cap = 2.06 g/kg Au. Skup (ecocenter 2025): 500-600 zł/kg. Au niższe niż dwustronne — brak złotego lidu.",
  },
  {
    id: "cpu_ceramic_nozki_blaszka",
    name: "Procesory ceramiczne złote nóżki (z blaszką aluminiową)",
    nameEn: "Ceramic CPU gold legs (with Al heat spreader)",
    category: "procesor",
    unit: "kg",
    weightPerPiece: 0.055,
    metalContentPerKg: {
      Au: { min: 1.5, max: 5.0, typical: 3.0 },
      Ag: { min: 0.8, max: 3.0, typical: 2.0 },
      Pt: { min: 0.0, max: 0.08, typical: 0.03 },
      Pd: { min: 0.02, max: 0.15, typical: 0.08 },
    },
    notes: "Ceramiczne procesory ze złotymi nóżkami i przyklejoną blaszką aluminiową (~55g/szt). Blaszka Al rozcieńcza zawartość Au.",
  },
  {
    id: "cpu_plastik_czarny",
    name: "Procesory plastikowe czarne",
    nameEn: "Black plastic CPUs",
    category: "procesor",
    unit: "kg",
    weightPerPiece: 0.070,
    metalContentPerKg: {
      Au: { min: 0.8, max: 3.5, typical: 2.0 },
      Ag: { min: 0.4, max: 2.5, typical: 1.2 },
      Pt: { min: 0.0, max: 0.05, typical: 0.018 },
      Pd: { min: 0.01, max: 0.10, typical: 0.05 },
    },
    notes: "Procesory w czarnej obudowie plastikowej (~70g/szt, np. AMD K6, Cyrix 486/586). GRF assay: AMD K6 batch = 1.97 g/kg Au, AMD K5 gold top = 6.48 g/kg (wyjątek — ma złotą czapę!). Skup (ecocenter 2025): 500-600 zł/kg. Plastikowa obudowa rozcieńcza koncentrację Au względem ceramicznych.",
  },
  {
    id: "cpu_slot1",
    name: "Procesory SLOT 1",
    nameEn: "Slot 1 CPUs",
    category: "procesor",
    unit: "kg",
    weightPerPiece: 0.150,
    metalContentPerKg: {
      Au: { min: 0.25, max: 0.90, typical: 0.55 },
      Ag: { min: 0.5, max: 2.5, typical: 1.3 },
      Pt: { min: 0.0, max: 0.02, typical: 0.008 },
      Pd: { min: 0.01, max: 0.06, typical: 0.03 },
    },
    notes: "Procesory Pentium II/III w kartridżu SLOT 1/SLOT A (~150g/szt z kartridżem).",
  },
  {
    id: "cpu_zielone_p3p4",
    name: "Procesory zielone (P3/P4)",
    nameEn: "Green CPUs (P3/P4)",
    category: "procesor",
    unit: "kg",
    weightPerPiece: 0.055,
    metalContentPerKg: {
      Au: { min: 0.25, max: 1.10, typical: 0.65 },
      Ag: { min: 0.20, max: 1.20, typical: 0.65 },
      Pt: { min: 0.0, max: 0.012, typical: 0.005 },
      Pd: { min: 0.006, max: 0.035, typical: 0.020 },
    },
    notes: "Procesory Pentium III/IV w zielonej obudowie organicznej (flip-chip PGA, ~55g/szt, socket 370/478). GRF assay: green fiber CPUs (Athlon, P4) = 0.76-0.80 g/kg Au dla typowych partii. Au z bond wires, substratu flip-chip i złoconych kontaktów. Ag z MLCC.",
  },
  {
    id: "cpu_zielone_c2d",
    name: "Procesory zielone z blaszką bez nóżek (C2D i nowsze)",
    nameEn: "Green CPUs no legs C2D+",
    category: "procesor",
    unit: "kg",
    weightPerPiece: 0.040,
    metalContentPerKg: {
      Au: { min: 0.05, max: 0.20, typical: 0.12 },
      Ag: { min: 0.2, max: 1.0, typical: 0.55 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.003, max: 0.02, typical: 0.01 },
    },
    notes: "Core 2 Duo i nowsze LGA (~40g/szt, bez nóżek). Mniej Au niż starsze — blaszka IHS z aluminium/miedzi rozcieńcza zawartość.",
  },
  {
    id: "cpu_zielone_p4_nozki",
    name: "Procesory zielone z blaszką z nóżkami (P4/Celeron)",
    nameEn: "Green CPUs with legs P4/Celeron",
    category: "procesor",
    unit: "kg",
    weightPerPiece: 0.050,
    metalContentPerKg: {
      Au: { min: 0.07, max: 0.25, typical: 0.15 },
      Ag: { min: 0.3, max: 1.2, typical: 0.65 },
      Pt: { min: 0.0, max: 0.007, typical: 0.003 },
      Pd: { min: 0.004, max: 0.025, typical: 0.013 },
    },
    notes: "Procesory P4/Celeron PGA478 (~50g/szt) z nóżkami i blaszką. metalContentPerKg uwzględnia plastik i blaszke IHS.",
  },
  {
    id: "cpu_intel",
    name: "Procesor CPU (Intel LGA, nowoczesny)",
    nameEn: "Intel LGA CPU (modern)",
    category: "procesor",
    unit: "piece",
    weightPerPiece: 0.030,
    metalContentPerKg: {
      Au: { min: 0.1, max: 0.5, typical: 0.3 },
      Ag: { min: 0.5, max: 2.0, typical: 1.0 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.0, max: 0.02, typical: 0.01 },
    },
    notes: "Procesory Intel Core i3/i5/i7/i9 LGA (~30g/szt). metalContentPerKg obliczone dla całego procesora.",
  },
  {
    id: "cpu_amd",
    name: "Procesor CPU (AMD AM4/AM5)",
    nameEn: "AMD AM4/AM5 CPU",
    category: "procesor",
    unit: "piece",
    weightPerPiece: 0.028,
    metalContentPerKg: {
      Au: { min: 0.08, max: 0.4, typical: 0.25 },
      Ag: { min: 0.4, max: 1.8, typical: 0.9 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.0, max: 0.02, typical: 0.01 },
    },
    notes: "Procesory AMD Ryzen AM4/AM5 (~28g/szt). metalContentPerKg obliczone dla całego procesora.",
  },

  // ─── PAMIĘCI RAM ──────────────────────────────────────────────────────────
  {
    id: "ram_srebrne",
    name: "Pamięci RAM (srebrne)",
    nameEn: "RAM Memory (silver contacts)",
    category: "pamiec",
    unit: "kg",
    weightPerPiece: 0.030,
    metalContentPerKg: {
      Au: { min: 0.02, max: 0.12, typical: 0.06 },
      Ag: { min: 0.15, max: 1.20, typical: 0.55 },
      Pt: { min: 0.0, max: 0.003, typical: 0.001 },
      Pd: { min: 0.0, max: 0.015, typical: 0.006 },
    },
    notes: "Kości RAM ze stykami cynowymi DDR3/DDR4/DDR5 (~30g/szt DIMM). Styki 'srebrne' to CYNA (Sn), nie srebro. Ag pochodzi TYLKO z lutowia SnAg (SAC305 = 3% Ag) i BME-MLCC — badania naukowe i GRF: 0.3-0.8 g/kg Ag dla RAM DDR3/DDR4 (JSDEWES, Res. Conserv. Recyclg. 2016). Au śladowe — głównie z bond wires IC (~0.04-0.08 g/kg). UWAGA: niskie wartości — materiał mało opłacalny do rafinacji indywidualnej; lepsza sprzedaż w skupie.",
  },
  {
    id: "ram_zlote",
    name: "Pamięci RAM (złote)",
    nameEn: "RAM Memory (gold contacts)",
    category: "pamiec",
    unit: "kg",
    weightPerPiece: 0.040,
    metalContentPerKg: {
      Au: { min: 0.60, max: 3.00, typical: 1.30 },
      Ag: { min: 0.10, max: 0.80, typical: 0.40 },
      Pt: { min: 0.0, max: 0.008, typical: 0.003 },
      Pd: { min: 0.02, max: 0.20, typical: 0.08 },
    },
    notes: "Kości RAM ze złotymi stykami SDR SDRAM/DDR1/DDR2 (~40g/szt DIMM) — bez aluminium. GŁÓWNE źródło Au: grube złocenie styków (20-30 µin Au over Ni). Phoenix Refining i GRF: DDR1 ~1.2-2.0 g/kg, DDR2 ~1.5-3.75 g/kg (wyższe dla ECC/server); konserwatywna wartość typowa 1.30 g/kg. Ag NISKA: lutowie Pb-Sn (pre-RoHS) bez Ag; Ag tylko z PME-MLCC ~0.2-0.4 g/kg. Skup: ~130-250 zł/kg.",
  },
  {
    id: "ram_simm",
    name: "Pamięć RAM (SIMM, vintage)",
    nameEn: "RAM Memory (SIMM, vintage)",
    category: "pamiec",
    unit: "kg",
    weightPerPiece: 0.040,
    metalContentPerKg: {
      Au: { min: 0.25, max: 1.50, typical: 0.85 },
      Ag: { min: 0.10, max: 1.20, typical: 0.50 },
      Pt: { min: 0.0, max: 0.015, typical: 0.008 },
      Pd: { min: 0.04, max: 0.35, typical: 0.18 },
    },
    notes: "Stare pamięci SIMM/EDO/FPM (30-pin/72-pin, ~40g/szt, przed ~1998). Grubsze złocenie styków niż DDR (~30-50 µin) ALE mniej kontaktów (30-72 vs 168-240 pinów) → per-kg Au NIŻSZE niż DDR1/DDR2. Phoenix Refining / GRF: EDO/FPM SIMM 0.3-0.6 g/kg; 30-pin SIMM (grubsze złocenie) do 1.2 g/kg. Wyższe Pd niż DDR — starsze PME-MLCC miały elektrody Pd-Ag. Lutowie Pb-Sn → brak Ag z lutowia.",
  },

  // ─── PAMIĘCI RAM ECC SERWEROWE ────────────────────────────────────────────
  {
    id: "ram_ecc_stare",
    name: "Pamięci RAM ECC (stare, DDR1/DDR2 serwerowe)",
    nameEn: "Server ECC RAM (old, DDR1/DDR2)",
    category: "pamiec",
    unit: "kg",
    weightPerPiece: 0.045,
    metalContentPerKg: {
      Au: { min: 1.50, max: 5.00, typical: 2.50 },
      Ag: { min: 0.10, max: 0.80, typical: 0.40 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.02, max: 0.25, typical: 0.10 },
    },
    notes: "Serwer ECC DIMM DDR1/DDR2 (~45g/szt, Registered/Fully Buffered ECC). Znacznie więcej złotych styków niż desktopowe RAM — więcej pinów i grubsze złocenie dla niezawodności serwerowej. Phoenix Refining/GRF: server DDR1 ECC 2.0-4.5 g/kg Au, DDR2 ECC reg. 1.5-3.0 g/kg. Lutowie Pb-Sn (pre-RoHS) → niskie Ag. Pd z PME-MLCC. Skup: 250-500 zł/kg.",
  },
  {
    id: "ram_ecc_nowe",
    name: "Pamięci RAM ECC (nowe, DDR3/DDR4 serwerowe)",
    nameEn: "Server ECC RAM (new, DDR3/DDR4)",
    category: "pamiec",
    unit: "kg",
    weightPerPiece: 0.060,
    metalContentPerKg: {
      Au: { min: 0.50, max: 2.00, typical: 1.00 },
      Ag: { min: 0.30, max: 1.50, typical: 0.80 },
      Pt: { min: 0.0, max: 0.003, typical: 0.001 },
      Pd: { min: 0.005, max: 0.04, typical: 0.015 },
    },
    notes: "Serwer ECC DIMM DDR3/DDR4 (~60g/szt, Registered/LR-DIMM). Styki BME z cienkim złoceniem (6-10 µin) — niższe Au niż stare ECC DDR1/DDR2. Ag z lutowia RoHS SAC305 (3% Ag) i MLCC. Pd z BME-MLCC (niskie). Skup: 100-200 zł/kg.",
  },

  // ─── KARTY GRAFICZNE / DŹWIĘKOWE ─────────────────────────────────────────
  {
    id: "karta_0bga",
    name: "Karty graficzne/dźwiękowe (0BGA)",
    nameEn: "Graphics/sound cards (0BGA)",
    category: "karta",
    unit: "kg",
    weightPerPiece: 0.35,
    metalContentPerKg: {
      Au: { min: 0.04, max: 0.15, typical: 0.08 },
      Ag: { min: 0.5, max: 2.0, typical: 1.1 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.005, max: 0.05, typical: 0.025 },
    },
    notes: "Karty graficzne i dźwiękowe bez układów BGA (~350g/szt) — bez śledzia, aluminium, wiatraków.",
  },
  {
    id: "karta_1bga",
    name: "Karty graficzne/dźwiękowe (1BGA)",
    nameEn: "Graphics/sound cards (1BGA)",
    category: "karta",
    unit: "kg",
    weightPerPiece: 0.40,
    metalContentPerKg: {
      Au: { min: 0.07, max: 0.25, typical: 0.14 },
      Ag: { min: 0.7, max: 2.8, typical: 1.5 },
      Pt: { min: 0.0, max: 0.008, typical: 0.003 },
      Pd: { min: 0.008, max: 0.07, typical: 0.035 },
    },
    notes: "Karty graficzne z jednym układem BGA (GPU) (~400g/szt) — bez śledzia, aluminium, wiatraków.",
  },

  {
    id: "karta_sieciowa",
    name: "Karty sieciowe / rozszerzeń (NIC, storage, modem)",
    nameEn: "Network / expansion cards (NIC, storage, modem)",
    category: "karta",
    unit: "kg",
    weightPerPiece: 0.12,
    metalContentPerKg: {
      Au: { min: 0.03, max: 0.15, typical: 0.07 },
      Ag: { min: 0.4, max: 1.8, typical: 1.0 },
      Pt: { min: 0.0, max: 0.004, typical: 0.002 },
      Pd: { min: 0.005, max: 0.045, typical: 0.022 },
    },
    notes: "Karty sieciowe (NIC), kontrolery RAID, karty SCSI, modemy PCI (~120g/szt) — bez śledzia. Mniejsze od kart graficznych, podobny skład do PCB klasy B. metalContentPerKg zbliżony do kart 0BGA z mniejszą ilością złoconych gniazd PCI/PCIe edge.",
  },

  // ─── DYSKI I NAPĘDY ───────────────────────────────────────────────────────
  {
    id: "hdd_caly",
    name: "Dyski twarde HDD (całe)",
    nameEn: "Complete HDD drives",
    category: "dysk",
    unit: "kg",
    weightPerPiece: 0.45,
    metalContentPerKg: {
      Au: { min: 0.005, max: 0.04, typical: 0.018 },
      Ag: { min: 0.05, max: 0.3, typical: 0.15 },
      Pt: { min: 0.002, max: 0.012, typical: 0.006 },
      Pd: { min: 0.005, max: 0.04, typical: 0.018 },
    },
    notes: "Całe dyski twarde HDD (~450g/szt). Platyna obecna w śladowych ilościach w warstwach magnetycznych talerzy (CoPtCr) — ok. 1-3 mg/dysk. metalContentPerKg uwzględnia całą obudowę, magnesy, głowice i PCB razem.",
  },
  {
    id: "naped_fdd_cdrom",
    name: "Napędy FDD/CD-ROM/DVD",
    nameEn: "FDD/CD-ROM/DVD drives",
    category: "dysk",
    unit: "kg",
    weightPerPiece: 0.40,
    metalContentPerKg: {
      Au: { min: 0.002, max: 0.015, typical: 0.007 },
      Ag: { min: 0.05, max: 0.3, typical: 0.12 },
      Pt: { min: 0.0, max: 0.01, typical: 0.003 },
      Pd: { min: 0.002, max: 0.02, typical: 0.008 },
    },
    notes: "Napędy dyskietek, CD-ROM i DVD (~400g/szt). Niski poziom metali szlachetnych — dominuje plastik i stal.",
  },
  {
    id: "hard_drive_head",
    name: "Głowice HDD",
    nameEn: "HDD Read/Write Heads",
    category: "dysk",
    unit: "kg",
    weightPerPiece: 0.003,
    metalContentPerKg: {
      Au: { min: 0.0, max: 0.05, typical: 0.02 },
      Ag: { min: 0.0, max: 0.1, typical: 0.04 },
      Pt: { min: 0.20, max: 0.80, typical: 0.45 },
      Pd: { min: 0.0, max: 0.05, typical: 0.02 },
    },
    notes: "Głowice magnetyczne dysków twardych (~3g/zestaw) — bogate w platynę z warstw magnetycznych Pt-Co stopu cienkowarstwowego. Zawartość Pt zależna od rocznika i producenta.",
  },

  // ─── URZĄDZENIA KOMPLETNE ─────────────────────────────────────────────────
  {
    id: "smartphone_bez_baterii",
    name: "Smartfony (bez baterii)",
    nameEn: "Smartphones (no battery)",
    category: "urzadzenie",
    unit: "kg",
    weightPerPiece: 0.17,
    metalContentPerKg: {
      Au: { min: 0.025, max: 0.08, typical: 0.045 },
      Ag: { min: 0.15, max: 0.5, typical: 0.28 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.008, max: 0.03, typical: 0.015 },
    },
    notes: "Całe smartfony bez baterii (~170g/szt). metalContentPerKg uwzględnia obudowę, wyświetlacz, PCB i wszystkie elementy.",
  },
  {
    id: "smartphone_z_bateria",
    name: "Smartfony (z bateriami)",
    nameEn: "Smartphones (with battery)",
    category: "urzadzenie",
    unit: "kg",
    weightPerPiece: 0.20,
    metalContentPerKg: {
      Au: { min: 0.015, max: 0.055, typical: 0.030 },
      Ag: { min: 0.08, max: 0.35, typical: 0.18 },
      Pt: { min: 0.0, max: 0.003, typical: 0.001 },
      Pd: { min: 0.005, max: 0.02, typical: 0.01 },
    },
    notes: "Całe smartfony z bateriami (~200g/szt). Bateria stanowi ~30-40% masy i rozcieńcza zawartość metali szlachetnych.",
  },
  {
    id: "phone_klawiat_bez_bat",
    name: "Telefony klawiaturowe (bez baterii)",
    nameEn: "Feature phones (no battery)",
    category: "urzadzenie",
    unit: "kg",
    weightPerPiece: 0.090,
    metalContentPerKg: {
      Au: { min: 0.05, max: 0.20, typical: 0.10 },
      Ag: { min: 0.3, max: 1.2, typical: 0.65 },
      Pt: { min: 0.0, max: 0.003, typical: 0.001 },
      Pd: { min: 0.008, max: 0.04, typical: 0.020 },
    },
    notes: "Stare telefony komórkowe z klawiaturą bez baterii (~90g/szt, np. Nokia, Motorola, Siemens).",
  },
  {
    id: "phone_klawiat_z_bat",
    name: "Telefony klawiaturowe (z bateriami)",
    nameEn: "Feature phones (with battery)",
    category: "urzadzenie",
    unit: "kg",
    weightPerPiece: 0.110,
    metalContentPerKg: {
      Au: { min: 0.025, max: 0.10, typical: 0.050 },
      Ag: { min: 0.15, max: 0.7, typical: 0.35 },
      Pt: { min: 0.0, max: 0.002, typical: 0.001 },
      Pd: { min: 0.004, max: 0.02, typical: 0.01 },
    },
    notes: "Stare telefony komórkowe z klawiaturą z bateriami (~110g/szt).",
  },
  {
    id: "phone_feature",
    name: "Telefon komórkowy klasyczny (szt.)",
    nameEn: "Feature phone per piece",
    category: "urzadzenie",
    unit: "piece",
    weightPerPiece: 0.08,
    metalContentPerKg: {
      Au: { min: 0.01, max: 0.04, typical: 0.02 },
      Ag: { min: 0.05, max: 0.2, typical: 0.12 },
      Pt: { min: 0.0, max: 0.002, typical: 0.001 },
      Pd: { min: 0.002, max: 0.01, typical: 0.006 },
    },
    notes: "Stary telefon komórkowy — wycena na sztuki (~80g/szt).",
  },
  {
    id: "laptop_bez_baterii",
    name: "Laptopy (bez baterii)",
    nameEn: "Laptops (no battery)",
    category: "urzadzenie",
    unit: "kg",
    weightPerPiece: 2.20,
    metalContentPerKg: {
      Au: { min: 0.04, max: 0.15, typical: 0.08 },
      Ag: { min: 0.3, max: 1.2, typical: 0.65 },
      Pt: { min: 0.0, max: 0.008, typical: 0.003 },
      Pd: { min: 0.008, max: 0.05, typical: 0.025 },
    },
    notes: "Całe laptopy bez baterii (~2.2 kg/szt). metalContentPerKg uwzględnia metalową obudowę, wyświetlacz i elektronikę — obudowa rozcieńcza zawartość Au.",
  },
  {
    id: "tablet_z_bateria",
    name: "Tablety (z bateriami)",
    nameEn: "Tablets (with battery)",
    category: "urzadzenie",
    unit: "kg",
    weightPerPiece: 0.55,
    metalContentPerKg: {
      Au: { min: 0.01, max: 0.06, typical: 0.028 },
      Ag: { min: 0.08, max: 0.35, typical: 0.18 },
      Pt: { min: 0.0, max: 0.003, typical: 0.001 },
      Pd: { min: 0.003, max: 0.02, typical: 0.009 },
    },
    notes: "Tablety z bateriami (iPad, Android, ~550g/szt). Bateria zajmuje ~30-40% masy.",
  },
  {
    id: "router",
    name: "Routery",
    nameEn: "Routers",
    category: "urzadzenie",
    unit: "kg",
    weightPerPiece: 0.40,
    metalContentPerKg: {
      Au: { min: 0.02, max: 0.10, typical: 0.05 },
      Ag: { min: 0.2, max: 1.0, typical: 0.5 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.005, max: 0.04, typical: 0.02 },
    },
    notes: "Routery sieciowe Wi-Fi/DSL (~400g/szt) — obudowa plastikowa z płytą PCB.",
  },
  {
    id: "dekoder_tv",
    name: "Dekodery telewizyjne",
    nameEn: "TV set-top boxes",
    category: "urzadzenie",
    unit: "kg",
    weightPerPiece: 0.70,
    metalContentPerKg: {
      Au: { min: 0.008, max: 0.04, typical: 0.018 },
      Ag: { min: 0.08, max: 0.4, typical: 0.20 },
      Pt: { min: 0.0, max: 0.003, typical: 0.001 },
      Pd: { min: 0.003, max: 0.02, typical: 0.008 },
    },
    notes: "Dekodery DVB-T/S/C (~700g/szt) — niski poziom metali szlachetnych.",
  },
  {
    id: "komputer_samochodowy",
    name: "Komputery samochodowe (całe)",
    nameEn: "Car ECU (complete)",
    category: "urzadzenie",
    unit: "kg",
    weightPerPiece: 1.00,
    metalContentPerKg: {
      Au: { min: 0.015, max: 0.06, typical: 0.03 },
      Ag: { min: 0.15, max: 0.8, typical: 0.4 },
      Pt: { min: 0.0, max: 0.008, typical: 0.003 },
      Pd: { min: 0.005, max: 0.04, typical: 0.018 },
    },
    notes: "Kompletne komputery samochodowe / sterowniki ECU (~1 kg/szt) — w metalowej obudowie.",
  },
  {
    id: "lcd_paski",
    name: "Paski z paneli LCD",
    nameEn: "LCD panel strips",
    category: "urzadzenie",
    unit: "kg",
    weightPerPiece: 0.10,
    metalContentPerKg: {
      Au: { min: 0.03, max: 0.12, typical: 0.06 },
      Ag: { min: 0.3, max: 1.5, typical: 0.8 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.008, max: 0.05, typical: 0.025 },
    },
    notes: "Taśmy FPC i płytki sterownicze z paneli LCD (~100g/szt) — złote styki i piny.",
  },

  // ─── ZASILACZE ────────────────────────────────────────────────────────────
  {
    id: "zasilacz_bez_kabla",
    name: "Zasilacze komputerowe (bez kabla)",
    nameEn: "Computer PSU (no cable)",
    category: "zasilacz",
    unit: "kg",
    weightPerPiece: 1.80,
    metalContentPerKg: {
      Au: { min: 0.003, max: 0.02, typical: 0.008 },
      Ag: { min: 0.05, max: 0.3, typical: 0.12 },
      Pt: { min: 0.0, max: 0.003, typical: 0.001 },
      Pd: { min: 0.002, max: 0.015, typical: 0.006 },
    },
    notes: "Zasilacze ATX/SFX bez kabli (~1.8 kg/szt). metalContentPerKg uwzględnia całą obudowę i elektronikę razem.",
  },
  {
    id: "zasilacz_z_kablem",
    name: "Zasilacze komputerowe (z kablem)",
    nameEn: "Computer PSU (with cable)",
    category: "zasilacz",
    unit: "kg",
    weightPerPiece: 2.20,
    metalContentPerKg: {
      Au: { min: 0.002, max: 0.015, typical: 0.006 },
      Ag: { min: 0.04, max: 0.25, typical: 0.10 },
      Pt: { min: 0.0, max: 0.002, typical: 0.001 },
      Pd: { min: 0.001, max: 0.012, typical: 0.005 },
    },
    notes: "Zasilacze ATX/SFX z kablami (~2.2 kg/szt). Kable miedzianie rozcieńczają zawartość metali szlachetnych.",
  },
  {
    id: "ladowarka_bez_kabla",
    name: "Ładowarki/zasilacze impulsowe (bez kabla)",
    nameEn: "Chargers/power adapters (no cable)",
    category: "zasilacz",
    unit: "kg",
    weightPerPiece: 0.20,
    metalContentPerKg: {
      Au: { min: 0.001, max: 0.008, typical: 0.003 },
      Ag: { min: 0.02, max: 0.15, typical: 0.06 },
      Pt: { min: 0.0, max: 0.001, typical: 0.0 },
      Pd: { min: 0.001, max: 0.008, typical: 0.003 },
    },
    notes: "Ładowarki i zasilacze impulsowe bez kabla (~200g/szt). Bardzo niski poziom metali szlachetnych.",
  },
  {
    id: "ladowarka_z_kablem",
    name: "Ładowarki/zasilacze impulsowe (z kablem)",
    nameEn: "Chargers/power adapters (with cable)",
    category: "zasilacz",
    unit: "kg",
    weightPerPiece: 0.30,
    metalContentPerKg: {
      Au: { min: 0.0005, max: 0.005, typical: 0.002 },
      Ag: { min: 0.01, max: 0.08, typical: 0.04 },
      Pt: { min: 0.0, max: 0.001, typical: 0.0 },
      Pd: { min: 0.0005, max: 0.005, typical: 0.002 },
    },
    notes: "Ładowarki i zasilacze z kablem (~300g/szt). Kabel miedziany rozcieńcza zawartość metali szlachetnych.",
  },

  // ─── UKŁADY SCALONE I KOMPONENTY ─────────────────────────────────────────
  {
    id: "ic_fpga",
    name: "FPGA / CPLD (preselekcjonowane)",
    nameEn: "FPGA / CPLD (preselected)",
    category: "ic",
    unit: "kg",
    weightPerPiece: 0.015,
    metalContentPerKg: {
      Au: { min: 0.3, max: 1.5, typical: 0.8 },
      Ag: { min: 2.0, max: 8.0, typical: 4.5 },
      Pt: { min: 0.0, max: 0.03, typical: 0.015 },
      Pd: { min: 0.02, max: 0.2, typical: 0.1 },
    },
    notes: "Programowalne układy logiczne FPGA/CPLD w obudowach BGA (~15g/szt). metalContentPerKg uwzględnia cały układ z obudową — nie trzeba osobno odliczać plastiku.",
  },
  {
    id: "ic_general",
    name: "Układy scalone IC (ogólne, preselekcjonowane)",
    nameEn: "Integrated Circuits (general, preselected)",
    category: "ic",
    unit: "kg",
    weightPerPiece: 0.006,
    metalContentPerKg: {
      Au: { min: 0.1, max: 0.8, typical: 0.4 },
      Ag: { min: 1.0, max: 5.0, typical: 2.5 },
      Pt: { min: 0.0, max: 0.02, typical: 0.01 },
      Pd: { min: 0.01, max: 0.1, typical: 0.05 },
    },
    notes: "Różne układy scalone DIP/SOIC/QFP (~6g/szt). metalContentPerKg uwzględnia całą obudowę z plastikiem/ceramiką — zawartość jest już podana dla materiału 'jak dostarczonego', bez osobnego odliczania.",
  },

  // ─── ZŁĄCZA ───────────────────────────────────────────────────────────────
  {
    id: "connectors_gold",
    name: "Złącza złocone (szpilki, krawędziowe)",
    nameEn: "Gold-plated connectors",
    category: "zlacza",
    unit: "kg",
    weightPerPiece: 0.006,
    requiresCleaning: true,
    cleanedMultiplier: { Au: 2.2, Ag: 2.2, Pt: 2.2, Pd: 2.2 },
    metalContentPerKg: {
      Au: { min: 1.0, max: 5.0, typical: 2.5 },
      Ag: { min: 0.5, max: 3.0, typical: 1.5 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.0, max: 0.05, typical: 0.02 },
    },
    notes: "Złote krawędziaki ISA/PCI, złocone szpilki (~6g/szt). metalContentPerKg uwzględnia plastikowe korpusy złączy — dane dla materiału 'jak dostarczonego'.",
  },
  {
    id: "connectors_eltra",
    name: "Złącza Eltra / podstawki przekaźnikowe (złocone)",
    nameEn: "Eltra / relay socket connectors (gold-plated)",
    category: "zlacza",
    unit: "kg",
    weightPerPiece: 0.020,
    requiresCleaning: true,
    cleanedMultiplier: { Au: 1.8, Ag: 1.8, Pt: 1.8, Pd: 1.8 },
    metalContentPerKg: {
      Au: { min: 0.5, max: 2.5, typical: 1.2 },
      Ag: { min: 0.3, max: 2.0, typical: 1.0 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.0, max: 0.03, typical: 0.012 },
    },
    notes: "Podstawki przekaźnikowe Eltra i podobne złącza przemysłowe ze złoconymi sprężynkami stykowymi (~20g/szt). metalContentPerKg uwzględnia plastikowy korpus i metalowe elementy razem — typowo 8-11 złoconych styków/szt.",
  },
  {
    id: "connectors_mixed",
    name: "Złącza mieszane (MIX)",
    nameEn: "Mixed connectors",
    category: "zlacza",
    unit: "kg",
    weightPerPiece: 0.012,
    requiresCleaning: true,
    cleanedMultiplier: { Au: 2.0, Ag: 2.0, Pt: 2.0, Pd: 2.0 },
    metalContentPerKg: {
      Au: { min: 0.2, max: 1.5, typical: 0.7 },
      Ag: { min: 0.3, max: 2.0, typical: 1.0 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.0, max: 0.02, typical: 0.01 },
    },
    notes: "Mieszane złącza z różnych urządzeń (~12g/szt). metalContentPerKg obliczone dla materiału z plastikiem i metalem razem.",
  },

  // ─── KONDENSATORY ─────────────────────────────────────────────────────────
  {
    id: "capacitors_tantalum",
    name: "Kondensatory tantalowe (preselekcjonowane)",
    nameEn: "Tantalum capacitors (preselected)",
    category: "kondensator",
    unit: "kg",
    weightPerPiece: 0.001,
    metalContentPerKg: {
      Au: { min: 0.0, max: 0.05, typical: 0.01 },
      Ag: { min: 0.5, max: 3.0, typical: 1.5 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.1, max: 1.0, typical: 0.5 },
    },
    notes: "Kondensatory tantalowe SMD i przewlekane (~1g/szt). metalContentPerKg uwzględnia całą obudowę kondensatora — bogate w pallad.",
  },
  {
    id: "capacitors_ceramic_mlcc",
    name: "Kondensatory ceramiczne MLCC (preselekcjonowane)",
    nameEn: "MLCC Ceramic capacitors (preselected)",
    category: "kondensator",
    unit: "kg",
    weightPerPiece: 0.0002,
    metalContentPerKg: {
      Au: { min: 0.0, max: 0.02, typical: 0.005 },
      Ag: { min: 1.0, max: 5.0, typical: 2.5 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.2, max: 2.0, typical: 1.0 },
    },
    notes: "Wielowarstwowe kondensatory ceramiczne MLCC (~0.2g/szt). metalContentPerKg uwzględnia ceramikę, elektrody i pokrywy razem — znaczna zawartość Ag i Pd.",
  },

  // ─── INNE ─────────────────────────────────────────────────────────────────
  {
    id: "catalytic_converter",
    name: "Katalizator samochodowy",
    nameEn: "Automotive catalytic converter",
    category: "inne",
    unit: "kg",
    weightPerPiece: 2.00,
    metalContentPerKg: {
      Au: { min: 0.0, max: 0.01, typical: 0.002 },
      Ag: { min: 0.0, max: 0.05, typical: 0.01 },
      Pt: { min: 0.5, max: 5.0, typical: 2.5 },
      Pd: { min: 1.0, max: 10.0, typical: 5.0 },
    },
    notes: "Ceramiczny rdzeń katalizatora samochodowego (~2 kg/szt bez obudowy). Bardzo bogaty w Pt i Pd — metalContentPerKg dla samego rdzenia ceramicznego.",
  },
  {
    id: "ufo_mix",
    name: "UFO — Nieznane/Mieszane",
    nameEn: "UFO - Unknown/Mixed scrap",
    category: "inne",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.03, max: 0.15, typical: 0.07 },
      Ag: { min: 0.3, max: 1.5, typical: 0.8 },
      Pt: { min: 0.0, max: 0.01, typical: 0.003 },
      Pd: { min: 0.0, max: 0.05, typical: 0.02 },
    },
    notes: "Niezidentyfikowane elementy elektroniczne, złom mieszany. metalContentPerKg to wartość uśredniona — rzeczywista zawartość może się znacznie różnić.",
  },
];

router.get("/materials/electronics", (_req, res) => {
  res.json(electronicMaterials);
});

export default router;
