import { Router, type IRouter } from "express";

const router: IRouter = Router();

const electronicMaterials = [
  {
    id: "pcb_standard",
    name: "Płytka PCB (standard FR4)",
    nameEn: "Standard PCB (FR4)",
    category: "pcb",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.03, max: 0.15, typical: 0.08 },
      Ag: { min: 0.5, max: 2.0, typical: 1.2 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.0, max: 0.05, typical: 0.02 },
    },
    notes: "Standardowe płytki drukowane z komputerów stacjonarnych i laptopów",
  },
  {
    id: "pcb_server",
    name: "Płytka PCB (serwerowa)",
    nameEn: "Server PCB",
    category: "pcb",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.1, max: 0.4, typical: 0.25 },
      Ag: { min: 1.0, max: 4.0, typical: 2.5 },
      Pt: { min: 0.0, max: 0.02, typical: 0.01 },
      Pd: { min: 0.01, max: 0.1, typical: 0.05 },
    },
    notes: "Płytki serwerowe zawierają więcej metali szlachetnych",
  },
  {
    id: "pcb_telecom",
    name: "Płytka PCB (telekomunikacyjna)",
    nameEn: "Telecom PCB",
    category: "pcb",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.15, max: 0.5, typical: 0.3 },
      Ag: { min: 1.5, max: 5.0, typical: 3.0 },
      Pt: { min: 0.0, max: 0.03, typical: 0.015 },
      Pd: { min: 0.02, max: 0.15, typical: 0.08 },
    },
    notes: "Urządzenia telekomunikacyjne, routery, przełączniki",
  },
  {
    id: "pcb_smd",
    name: "Elementy SMD / BGA",
    nameEn: "SMD Components / BGA",
    category: "pcb",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.2, max: 1.0, typical: 0.5 },
      Ag: { min: 2.0, max: 8.0, typical: 4.0 },
      Pt: { min: 0.0, max: 0.05, typical: 0.02 },
      Pd: { min: 0.05, max: 0.3, typical: 0.15 },
    },
    notes: "Drobne elementy montowane powierzchniowo, kulki BGA",
  },
  {
    id: "cpu_intel",
    name: "Procesor CPU (Intel Socket)",
    nameEn: "Intel Socket CPU",
    category: "processor",
    unit: "piece",
    metalContentPerKg: {
      Au: { min: 0.1, max: 0.5, typical: 0.3 },
      Ag: { min: 0.5, max: 2.0, typical: 1.0 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.0, max: 0.02, typical: 0.01 },
    },
    notes: "Procesory Intel LGA (jednostka: szt, przeliczenie na 1 kg = ~33 szt)",
  },
  {
    id: "cpu_amd",
    name: "Procesor CPU (AMD Socket)",
    nameEn: "AMD Socket CPU",
    category: "processor",
    unit: "piece",
    metalContentPerKg: {
      Au: { min: 0.08, max: 0.4, typical: 0.25 },
      Ag: { min: 0.4, max: 1.8, typical: 0.9 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.0, max: 0.02, typical: 0.01 },
    },
    notes: "Procesory AMD AM4/AM5",
  },
  {
    id: "cpu_ceramic",
    name: "Procesor CPU (ceramiczny, vintage)",
    nameEn: "Ceramic CPU (vintage)",
    category: "processor",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 1.0, max: 4.0, typical: 2.5 },
      Ag: { min: 2.0, max: 8.0, typical: 5.0 },
      Pt: { min: 0.0, max: 0.1, typical: 0.05 },
      Pd: { min: 0.05, max: 0.3, typical: 0.15 },
    },
    notes: "Stare procesory ceramiczne (Intel 286/386/486, Pentium Pro) - bardzo bogate w złoto",
  },
  {
    id: "ram_dimm",
    name: "Pamięć RAM (DIMM DDR)",
    nameEn: "RAM Memory (DIMM DDR)",
    category: "memory",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.05, max: 0.2, typical: 0.12 },
      Ag: { min: 0.8, max: 3.0, typical: 1.8 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.01, max: 0.08, typical: 0.04 },
    },
    notes: "Kości pamięci RAM, wszystkie generacje DDR",
  },
  {
    id: "ram_simm",
    name: "Pamięć RAM (SIMM, vintage)",
    nameEn: "RAM Memory (SIMM, vintage)",
    category: "memory",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.3, max: 1.0, typical: 0.6 },
      Ag: { min: 2.0, max: 6.0, typical: 3.5 },
      Pt: { min: 0.0, max: 0.02, typical: 0.01 },
      Pd: { min: 0.02, max: 0.15, typical: 0.08 },
    },
    notes: "Stare pamięci SIMM/EDO/FPM - bogatsze w złoto",
  },
  {
    id: "ic_general",
    name: "Układy scalone IC (ogólne)",
    nameEn: "Integrated Circuits (general)",
    category: "ic",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.1, max: 0.8, typical: 0.4 },
      Ag: { min: 1.0, max: 5.0, typical: 2.5 },
      Pt: { min: 0.0, max: 0.02, typical: 0.01 },
      Pd: { min: 0.01, max: 0.1, typical: 0.05 },
    },
    notes: "Różne układy scalone DIP/SOIC/QFP",
  },
  {
    id: "ic_fpga",
    name: "FPGA / CPLD",
    nameEn: "FPGA / CPLD",
    category: "ic",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.3, max: 1.5, typical: 0.8 },
      Ag: { min: 2.0, max: 8.0, typical: 4.5 },
      Pt: { min: 0.0, max: 0.03, typical: 0.015 },
      Pd: { min: 0.02, max: 0.2, typical: 0.1 },
    },
    notes: "Programowalne układy logiczne w obudowach BGA",
  },
  {
    id: "connectors_gold",
    name: "Złącza złocone (szpilki, krawędziowe)",
    nameEn: "Gold-plated connectors (pins, edge)",
    category: "connector",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 1.0, max: 5.0, typical: 2.5 },
      Ag: { min: 0.5, max: 3.0, typical: 1.5 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.0, max: 0.05, typical: 0.02 },
    },
    notes: "Złote krawędziaki ISA/PCI, złocone szpilki, złącza DB9/DB25",
  },
  {
    id: "connectors_mixed",
    name: "Złącza mieszane (MIX)",
    nameEn: "Mixed connectors",
    category: "connector",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.2, max: 1.5, typical: 0.7 },
      Ag: { min: 0.3, max: 2.0, typical: 1.0 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.0, max: 0.02, typical: 0.01 },
    },
    notes: "Mieszane złącza z różnych typów urządzeń",
  },
  {
    id: "capacitors_tantalum",
    name: "Kondensatory tantalowe",
    nameEn: "Tantalum capacitors",
    category: "capacitor",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.0, max: 0.05, typical: 0.01 },
      Ag: { min: 0.5, max: 3.0, typical: 1.5 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.1, max: 1.0, typical: 0.5 },
    },
    notes: "Kondensatory SMD i przewlekane tantalowe - bogate w pallad",
  },
  {
    id: "capacitors_ceramic_mlcc",
    name: "Kondensatory ceramiczne MLCC",
    nameEn: "MLCC Ceramic capacitors",
    category: "capacitor",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.0, max: 0.02, typical: 0.005 },
      Ag: { min: 1.0, max: 5.0, typical: 2.5 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.2, max: 2.0, typical: 1.0 },
    },
    notes: "Wielowarstwowe kondensatory ceramiczne - znaczna zawartość srebra i palladu",
  },
  {
    id: "phone_smartphone",
    name: "Smartfon",
    nameEn: "Smartphone",
    category: "phone",
    unit: "piece",
    metalContentPerKg: {
      Au: { min: 0.02, max: 0.06, typical: 0.04 },
      Ag: { min: 0.1, max: 0.4, typical: 0.25 },
      Pt: { min: 0.0, max: 0.005, typical: 0.002 },
      Pd: { min: 0.005, max: 0.02, typical: 0.012 },
    },
    notes: "Smartfony (przeliczenie: 1 kg = ~6-8 szt smartfonów)",
  },
  {
    id: "phone_feature",
    name: "Telefon komórkowy (klasyczny)",
    nameEn: "Feature phone (classic mobile)",
    category: "phone",
    unit: "piece",
    metalContentPerKg: {
      Au: { min: 0.01, max: 0.04, typical: 0.02 },
      Ag: { min: 0.05, max: 0.2, typical: 0.12 },
      Pt: { min: 0.0, max: 0.002, typical: 0.001 },
      Pd: { min: 0.002, max: 0.01, typical: 0.006 },
    },
    notes: "Stare telefony komórkowe, Nokia, Ericsson itp.",
  },
  {
    id: "laptop_complete",
    name: "Laptop (kompletny, bez baterii)",
    nameEn: "Laptop (complete, no battery)",
    category: "laptop",
    unit: "piece",
    metalContentPerKg: {
      Au: { min: 0.05, max: 0.2, typical: 0.12 },
      Ag: { min: 0.5, max: 2.0, typical: 1.2 },
      Pt: { min: 0.0, max: 0.01, typical: 0.005 },
      Pd: { min: 0.01, max: 0.06, typical: 0.035 },
    },
    notes: "Cały laptop ~2-3 kg, przeliczenie na 1 kg masy",
  },
  {
    id: "ufo_mix",
    name: "UFO - Nieznane/Mieszane",
    nameEn: "UFO - Unknown/Mixed scrap",
    category: "other",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.03, max: 0.15, typical: 0.07 },
      Ag: { min: 0.3, max: 1.5, typical: 0.8 },
      Pt: { min: 0.0, max: 0.01, typical: 0.003 },
      Pd: { min: 0.0, max: 0.05, typical: 0.02 },
    },
    notes: "Niezidentyfikowane elementy elektroniczne, złom mieszany",
  },
  {
    id: "hard_drive_head",
    name: "Głowice HDD",
    nameEn: "HDD Read/Write Heads",
    category: "other",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.0, max: 0.05, typical: 0.02 },
      Ag: { min: 0.0, max: 0.1, typical: 0.04 },
      Pt: { min: 0.5, max: 2.0, typical: 1.2 },
      Pd: { min: 0.0, max: 0.05, typical: 0.02 },
    },
    notes: "Głowice magnetyczne dysków twardych - bogate w platynę",
  },
  {
    id: "catalytic_converter",
    name: "Katalizator samochodowy",
    nameEn: "Automotive catalytic converter",
    category: "other",
    unit: "kg",
    metalContentPerKg: {
      Au: { min: 0.0, max: 0.01, typical: 0.002 },
      Ag: { min: 0.0, max: 0.05, typical: 0.01 },
      Pt: { min: 0.5, max: 5.0, typical: 2.5 },
      Pd: { min: 1.0, max: 10.0, typical: 5.0 },
    },
    notes: "Ceramiczny rdzeń katalizatora - bardzo bogaty w Pt i Pd",
  },
];

router.get("/materials/electronics", (_req, res) => {
  res.json(electronicMaterials);
});

export default router;
