// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scan/ScanLineA.tsx": () => import("../components/mockups/scan/ScanLineA.tsx"),
  "./components/mockups/scan/ScanLineB.tsx": () => import("../components/mockups/scan/ScanLineB.tsx")
};
